# References

Belsey, D. A., Kuh, E., & Welsch, R. E. (1980). Regression Diagnostics: Identifying Influential Data and Sources of Collinearity. Hoboken, NJ: John Wiley & Sons, Inc.

Bollen, K. A., & Jackman, R. W. (1985). Regression Diagnostics: An Expository Treatment of Outliers and Influential Cases. *Sociological Methods & Research*, *13*(4), 510–542.

Chang, W. (2020). [R Graphics Cookbook](https://r-graphics.org/) (2nd ed.). Sebastopol, CA: O’Reilly.

Colquhoun, D. (2014). [An investigation of the false discovery rate and the misinterpretation of p-values](https://doi.org/10.1098/rsos.140216). *Royal Society Open Science*, *1*, 140216. doi: 10.1098/rsos.140216

Curtice, J., Hudson, N., and Montagu, I. (eds.) (2020) [*British Social
Attitudes: The 37th Report*](https://www.bsa.natcen.ac.uk/latest-report/british-social-attitudes-37/fairness-and-justice-in-britain.aspx). London: The National Centre for Social Research.

European Social Survey Round 9 Data (2018). Data file edition 2.0. NSD - Norwegian Centre for Research Data, Norway – Data Archive and distributor of ESS data for ESS ERIC. doi:10.21338/NSD-ESS9-2018.

Fox, J. & Weisberg, S. (2019). *An R Companion to Applied Regression*, Third Edition, Sage.

Gelman, A., & Hill, J. (2007). *Data Analysis Using Regression and Multilevel/Hierarchical Models*. Cambridge: Cambridge University Press.

Greenland, S., Senn, S. J., Rothman, K. J., Carlin, J. B., Poole, C., Goodman, S. N., & Altman, D. G. (2016). [Statistical tests, P values, confidence intervals, and power: a guide to misinterpretations](https://link.springer.com/article/10.1007/s10654-016-0149-3). *European Journal of Epidemiology*, *31*, 337–350. doi: 10.1007/s10654-016-0149-3

Healy, K. (2019). [Data Visualization: A Practical Introduction](https://socviz.co/). Princeton University Press.

Lumley, T. (2010). *Complex Surveys: A Guide to Analysis Using R.* Hoboken, NJ: John Wiley & Sons, Inc.

Lüdecke D (2018). [ggeffects: Tidy Data Frames of Marginal Effects from Regression Models](https://joss.theoj.org/papers/10.21105/joss.00772). Journal of Open Source Software, 3(26), 772. doi: 10.21105/joss.00772

Mroz, T. A. (1987). The sensitivity of an empirical model of married women's hours of work to economic and statistical assumptions. *Econometrica*, *55*, 765–799.

Noether, G. E. (1984). Nonparametrics: The Early Years-Impressions and Recollections. *American Statistician*, *38*, 173-178]

Rafi, Z., & Greenland, S. (2020). [Semantic and cognitive tools to aid statistical science: replace confidence and significance by compatibility and surprise](https://doi.org/10.1186/s12874-020-01105-9). BMC Medical Research Methodology, 20(1), 244. doi: 10.1186/s12874-020-01105-9

Tingley, D., Yamamoto, T., Hirose, K., Keele, L., & Imai, K. (2014). [mediation: R Package for Causal Mediation Analysis](https://www.jstatsoft.org/article/view/v059i05). *Journal of Statistical Software*, *59*(5), 1–38. doi: 10.18637/jss.v059.i05

Van Buuren, S. (2018). [Flexible Imputation of Missing Data (2nd Edition)](https://stefvanbuuren.name/fimd/). Chapman & Hall/CRC. Boca Raton, FL.

Wickham, H., & Grolemund, G. (2017). [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data](http://r4ds.had.co.nz/). Sebastopol, CA: O’Reilly.

Wolfowitz, J. (1942). Additive Partition Functions and a Class of Statistical Hypotheses. *Annals of Mathematical Statistics*, *13*, 247-279
