<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Categorical predictors and interactions | Using R for social research</title>
  <meta name="description" content="These are some notes on using R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Categorical predictors and interactions | Using R for social research" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="These are some notes on using R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Categorical predictors and interactions | Using R for social research" />
  
  <meta name="twitter:description" content="These are some notes on using R" />
  

<meta name="author" content="Andi Fugard (they/them)  (almost@gmail.com, @InductiveStep)" />


<meta name="date" content="2020-12-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="linear-regression-diagnostics.html"/>
<link rel="next" href="logistic-regression.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<link href="libs/table1-1.0/table1_defaults.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="starting-rstudio.html"><a href="starting-rstudio.html"><i class="fa fa-check"></i><b>1</b> Starting RStudio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="starting-rstudio.html"><a href="starting-rstudio.html#download-install-and-run"><i class="fa fa-check"></i><b>1.1</b> Download, install, and run</a></li>
<li class="chapter" data-level="1.2" data-path="starting-rstudio.html"><a href="starting-rstudio.html#make-a-new-r-notebook-file"><i class="fa fa-check"></i><b>1.2</b> Make a new R Notebook file</a></li>
<li class="chapter" data-level="1.3" data-path="starting-rstudio.html"><a href="starting-rstudio.html#save-the-file"><i class="fa fa-check"></i><b>1.3</b> Save the file</a></li>
<li class="chapter" data-level="1.4" data-path="starting-rstudio.html"><a href="starting-rstudio.html#run-the-example-r-command"><i class="fa fa-check"></i><b>1.4</b> Run the example R command</a></li>
<li class="chapter" data-level="1.5" data-path="starting-rstudio.html"><a href="starting-rstudio.html#clear-it-and-try-a-sum"><i class="fa fa-check"></i><b>1.5</b> Clear it and try a sum</a></li>
<li class="chapter" data-level="1.6" data-path="starting-rstudio.html"><a href="starting-rstudio.html#did-that-help"><i class="fa fa-check"></i><b>1.6</b> Did that help?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="starting-r.html"><a href="starting-r.html"><i class="fa fa-check"></i><b>2</b> Starting R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="starting-r.html"><a href="starting-r.html#arithmetic"><i class="fa fa-check"></i><b>2.1</b> Arithmetic</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="starting-r.html"><a href="starting-r.html#activities"><i class="fa fa-check"></i><b>2.1.1</b> Activities</a></li>
<li class="chapter" data-level="2.1.2" data-path="starting-r.html"><a href="starting-r.html#answers"><i class="fa fa-check"></i><b>2.1.2</b> Answers</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="starting-r.html"><a href="starting-r.html#variables"><i class="fa fa-check"></i><b>2.2</b> Variables</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="starting-r.html"><a href="starting-r.html#activity"><i class="fa fa-check"></i><b>2.2.1</b> Activity</a></li>
<li class="chapter" data-level="2.2.2" data-path="starting-r.html"><a href="starting-r.html#answer"><i class="fa fa-check"></i><b>2.2.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="starting-r.html"><a href="starting-r.html#a-note-on-variable-names"><i class="fa fa-check"></i><b>2.3</b> A note on variable names</a></li>
<li class="chapter" data-level="2.4" data-path="starting-r.html"><a href="starting-r.html#vectors"><i class="fa fa-check"></i><b>2.4</b> Vectors</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="starting-r.html"><a href="starting-r.html#activity-1"><i class="fa fa-check"></i><b>2.4.1</b> Activity</a></li>
<li class="chapter" data-level="2.4.2" data-path="starting-r.html"><a href="starting-r.html#answer-1"><i class="fa fa-check"></i><b>2.4.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="starting-r.html"><a href="starting-r.html#functions"><i class="fa fa-check"></i><b>2.5</b> Functions</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="starting-r.html"><a href="starting-r.html#activity-2"><i class="fa fa-check"></i><b>2.5.1</b> Activity</a></li>
<li class="chapter" data-level="2.5.2" data-path="starting-r.html"><a href="starting-r.html#answer-2"><i class="fa fa-check"></i><b>2.5.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="starting-r.html"><a href="starting-r.html#more-functions"><i class="fa fa-check"></i><b>2.6</b> More functions</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="starting-r.html"><a href="starting-r.html#activity-3"><i class="fa fa-check"></i><b>2.6.1</b> Activity</a></li>
<li class="chapter" data-level="2.6.2" data-path="starting-r.html"><a href="starting-r.html#answer-3"><i class="fa fa-check"></i><b>2.6.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="starting-r.html"><a href="starting-r.html#data-frames"><i class="fa fa-check"></i><b>2.7</b> Data frames</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="starting-r.html"><a href="starting-r.html#activity-4"><i class="fa fa-check"></i><b>2.7.1</b> Activity</a></li>
<li class="chapter" data-level="2.7.2" data-path="starting-r.html"><a href="starting-r.html#answer-4"><i class="fa fa-check"></i><b>2.7.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="starting-r.html"><a href="starting-r.html#loading-data-frames-from-a-file"><i class="fa fa-check"></i><b>2.8</b> Loading data frames from a file</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="starting-r.html"><a href="starting-r.html#activity-5"><i class="fa fa-check"></i><b>2.8.1</b> Activity</a></li>
<li class="chapter" data-level="2.8.2" data-path="starting-r.html"><a href="starting-r.html#answer-5"><i class="fa fa-check"></i><b>2.8.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="starting-r.html"><a href="starting-r.html#packages"><i class="fa fa-check"></i><b>2.9</b> Packages</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="starting-r.html"><a href="starting-r.html#activity-6"><i class="fa fa-check"></i><b>2.9.1</b> Activity</a></li>
<li class="chapter" data-level="2.9.2" data-path="starting-r.html"><a href="starting-r.html#answer-6"><i class="fa fa-check"></i><b>2.9.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="starting-r.html"><a href="starting-r.html#the-end"><i class="fa fa-check"></i><b>2.10</b> The end!</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html"><i class="fa fa-check"></i><b>3</b> Visualising data in the tidyverse</a>
<ul>
<li class="chapter" data-level="3.1" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#getting-setup"><i class="fa fa-check"></i><b>3.1</b> Getting setup</a></li>
<li class="chapter" data-level="3.2" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#an-interlude-on-functions"><i class="fa fa-check"></i><b>3.2</b> An interlude on functions</a></li>
<li class="chapter" data-level="3.3" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#a-scatterplot-in-ggplot"><i class="fa fa-check"></i><b>3.3</b> A scatterplot in ggplot</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#warm-up-activity"><i class="fa fa-check"></i><b>3.3.1</b> Warm-up activity</a></li>
<li class="chapter" data-level="3.3.2" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#answer-7"><i class="fa fa-check"></i><b>3.3.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#another-aesthetic-colour"><i class="fa fa-check"></i><b>3.4</b> Another aesthetic: colour</a></li>
<li class="chapter" data-level="3.5" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#another-geom-jitter"><i class="fa fa-check"></i><b>3.5</b> Another geom: jitter</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#activity-to-develop-your-help-searching-skill"><i class="fa fa-check"></i><b>3.5.1</b> Activity to develop your help-searching skill!</a></li>
<li class="chapter" data-level="3.5.2" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#answer-8"><i class="fa fa-check"></i><b>3.5.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#aggregatingsummarising-data-by-group"><i class="fa fa-check"></i><b>3.6</b> Aggregating/summarising data by group</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#activity-7"><i class="fa fa-check"></i><b>3.6.1</b> Activity</a></li>
<li class="chapter" data-level="3.6.2" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#answer-9"><i class="fa fa-check"></i><b>3.6.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#pipes"><i class="fa fa-check"></i><b>3.7</b> Pipes</a></li>
<li class="chapter" data-level="3.8" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#plot-the-mean-life-expectancy-by-continent"><i class="fa fa-check"></i><b>3.8</b> Plot the mean life expectancy by continent</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#actvity"><i class="fa fa-check"></i><b>3.8.1</b> Actvity</a></li>
<li class="chapter" data-level="3.8.2" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#answer-10"><i class="fa fa-check"></i><b>3.8.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#yet-another-geom-line"><i class="fa fa-check"></i><b>3.9</b> Yet another geom: line</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#activity-8"><i class="fa fa-check"></i><b>3.9.1</b> Activity</a></li>
<li class="chapter" data-level="3.9.2" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#answer-11"><i class="fa fa-check"></i><b>3.9.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#filtering-data-along-the-pipeline"><i class="fa fa-check"></i><b>3.10</b> Filtering data along the pipeline</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#activity-9"><i class="fa fa-check"></i><b>3.10.1</b> Activity</a></li>
<li class="chapter" data-level="3.10.2" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#answer-12"><i class="fa fa-check"></i><b>3.10.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#other-handy-tools-select-slice-bind-and-arrange"><i class="fa fa-check"></i><b>3.11</b> Other handy tools: select, slice, bind, and arrange</a></li>
<li class="chapter" data-level="3.12" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#filtering-for-members-of-a-vector"><i class="fa fa-check"></i><b>3.12</b> Filtering for members of a vector</a></li>
<li class="chapter" data-level="3.13" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#final-challenge"><i class="fa fa-check"></i><b>3.13</b> Final challenge</a>
<ul>
<li class="chapter" data-level="3.13.1" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#activity-10"><i class="fa fa-check"></i><b>3.13.1</b> Activity</a></li>
<li class="chapter" data-level="3.13.2" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#answer-13"><i class="fa fa-check"></i><b>3.13.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="3.14" data-path="visualising-data-in-the-tidyverse.html"><a href="visualising-data-in-the-tidyverse.html#more-ideas-for-visualisations"><i class="fa fa-check"></i><b>3.14</b> More ideas for visualisations</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="p-values-and-confidence-intervals.html"><a href="p-values-and-confidence-intervals.html"><i class="fa fa-check"></i><b>4</b> P-values and confidence intervals</a>
<ul>
<li class="chapter" data-level="4.1" data-path="p-values-and-confidence-intervals.html"><a href="p-values-and-confidence-intervals.html#correlation-recap"><i class="fa fa-check"></i><b>4.1</b> Correlation recap</a></li>
<li class="chapter" data-level="4.2" data-path="p-values-and-confidence-intervals.html"><a href="p-values-and-confidence-intervals.html#testing-null-hypotheses"><i class="fa fa-check"></i><b>4.2</b> Testing null-hypotheses</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="p-values-and-confidence-intervals.html"><a href="p-values-and-confidence-intervals.html#what-can-samples-look-like-when-the-true-correlation-is-0"><i class="fa fa-check"></i><b>4.2.1</b> What can samples look like when the true correlation is 0?</a></li>
<li class="chapter" data-level="4.2.2" data-path="p-values-and-confidence-intervals.html"><a href="p-values-and-confidence-intervals.html#understanding-actual-data-in-relation-to-these-simulations"><i class="fa fa-check"></i><b>4.2.2</b> Understanding actual data in relation to these simulations</a></li>
<li class="chapter" data-level="4.2.3" data-path="p-values-and-confidence-intervals.html"><a href="p-values-and-confidence-intervals.html#so-what-is-a-p-value"><i class="fa fa-check"></i><b>4.2.3</b> So, what is a p-value?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="p-values-and-confidence-intervals.html"><a href="p-values-and-confidence-intervals.html#confidence-intervals"><i class="fa fa-check"></i><b>4.3</b> Confidence intervals</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="p-values-and-confidence-intervals.html"><a href="p-values-and-confidence-intervals.html#simulating-confidence"><i class="fa fa-check"></i><b>4.3.1</b> Simulating confidence</a></li>
<li class="chapter" data-level="4.3.2" data-path="p-values-and-confidence-intervals.html"><a href="p-values-and-confidence-intervals.html#what-is-a-confidence-interval-then"><i class="fa fa-check"></i><b>4.3.2</b> What is a confidence interval, then?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="p-values-and-confidence-intervals.html"><a href="p-values-and-confidence-intervals.html#further-reading"><i class="fa fa-check"></i><b>4.4</b> Further reading</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>5</b> Linear regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="linear-regression.html"><a href="linear-regression.html#before-we-begin"><i class="fa fa-check"></i><b>5.1</b> Before we begin</a></li>
<li class="chapter" data-level="5.2" data-path="linear-regression.html"><a href="linear-regression.html#the-dataset"><i class="fa fa-check"></i><b>5.2</b> The dataset</a></li>
<li class="chapter" data-level="5.3" data-path="linear-regression.html"><a href="linear-regression.html#interlude-on-methodology"><i class="fa fa-check"></i><b>5.3</b> Interlude on methodology</a></li>
<li class="chapter" data-level="5.4" data-path="linear-regression.html"><a href="linear-regression.html#descriptives"><i class="fa fa-check"></i><b>5.4</b> Descriptives</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="linear-regression.html"><a href="linear-regression.html#activity-11"><i class="fa fa-check"></i><b>5.4.1</b> Activity</a></li>
<li class="chapter" data-level="5.4.2" data-path="linear-regression.html"><a href="linear-regression.html#answer-14"><i class="fa fa-check"></i><b>5.4.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="linear-regression.html"><a href="linear-regression.html#prep-to-understand-the-simplest-regression-model"><i class="fa fa-check"></i><b>5.5</b> Prep to understand the simplest regression model</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="linear-regression.html"><a href="linear-regression.html#activity-12"><i class="fa fa-check"></i><b>5.5.1</b> Activity</a></li>
<li class="chapter" data-level="5.5.2" data-path="linear-regression.html"><a href="linear-regression.html#answer-15"><i class="fa fa-check"></i><b>5.5.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="linear-regression.html"><a href="linear-regression.html#the-simplest-regression-model-intercept-only-model"><i class="fa fa-check"></i><b>5.6</b> The simplest regression model: intercept-only model</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="linear-regression.html"><a href="linear-regression.html#activity-13"><i class="fa fa-check"></i><b>5.6.1</b> Activity</a></li>
<li class="chapter" data-level="5.6.2" data-path="linear-regression.html"><a href="linear-regression.html#answer-16"><i class="fa fa-check"></i><b>5.6.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="linear-regression.html"><a href="linear-regression.html#adding-a-slope-to-the-regression-model"><i class="fa fa-check"></i><b>5.7</b> Adding a slope to the regression model</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="linear-regression.html"><a href="linear-regression.html#activity-14"><i class="fa fa-check"></i><b>5.7.1</b> Activity</a></li>
<li class="chapter" data-level="5.7.2" data-path="linear-regression.html"><a href="linear-regression.html#answer-17"><i class="fa fa-check"></i><b>5.7.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="linear-regression.html"><a href="linear-regression.html#residuals"><i class="fa fa-check"></i><b>5.8</b> Residuals</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="linear-regression.html"><a href="linear-regression.html#activity-15"><i class="fa fa-check"></i><b>5.8.1</b> Activity</a></li>
<li class="chapter" data-level="5.8.2" data-path="linear-regression.html"><a href="linear-regression.html#answer-18"><i class="fa fa-check"></i><b>5.8.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="linear-regression.html"><a href="linear-regression.html#comparing-models"><i class="fa fa-check"></i><b>5.9</b> Comparing models</a></li>
<li class="chapter" data-level="5.10" data-path="linear-regression.html"><a href="linear-regression.html#regression-with-two-or-more-predictors"><i class="fa fa-check"></i><b>5.10</b> Regression with two or more predictors</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="linear-regression.html"><a href="linear-regression.html#activity-16"><i class="fa fa-check"></i><b>5.10.1</b> Activity</a></li>
<li class="chapter" data-level="5.10.2" data-path="linear-regression.html"><a href="linear-regression.html#answer-19"><i class="fa fa-check"></i><b>5.10.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="linear-regression.html"><a href="linear-regression.html#interpreting-regression-models-with-two-or-more-predictors"><i class="fa fa-check"></i><b>5.11</b> Interpreting regression models with two or more predictors</a></li>
<li class="chapter" data-level="5.12" data-path="linear-regression.html"><a href="linear-regression.html#optional-that-pesky-negative-intercept"><i class="fa fa-check"></i><b>5.12</b> Optional: that pesky negative intercept</a>
<ul>
<li class="chapter" data-level="5.12.1" data-path="linear-regression.html"><a href="linear-regression.html#activity-17"><i class="fa fa-check"></i><b>5.12.1</b> Activity</a></li>
<li class="chapter" data-level="5.12.2" data-path="linear-regression.html"><a href="linear-regression.html#answer-20"><i class="fa fa-check"></i><b>5.12.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="5.13" data-path="linear-regression.html"><a href="linear-regression.html#finally-confidence-intervals"><i class="fa fa-check"></i><b>5.13</b> Finally: confidence intervals</a></li>
<li class="chapter" data-level="5.14" data-path="linear-regression.html"><a href="linear-regression.html#very-optional-extras"><i class="fa fa-check"></i><b>5.14</b> Very optional extras</a>
<ul>
<li class="chapter" data-level="5.14.1" data-path="linear-regression.html"><a href="linear-regression.html#making-functions"><i class="fa fa-check"></i><b>5.14.1</b> Making functions</a></li>
<li class="chapter" data-level="5.14.2" data-path="linear-regression.html"><a href="linear-regression.html#another-way-to-make-scatterplots-ggally"><i class="fa fa-check"></i><b>5.14.2</b> Another way to make scatterplots: GGally</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html"><i class="fa fa-check"></i><b>6</b> Linear regression diagnostics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#before-we-begin-1"><i class="fa fa-check"></i><b>6.1</b> Before we begin</a></li>
<li class="chapter" data-level="6.2" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#the-dataset-1"><i class="fa fa-check"></i><b>6.2</b> The dataset</a></li>
<li class="chapter" data-level="6.3" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#fit-a-regression-model"><i class="fa fa-check"></i><b>6.3</b> Fit a regression model</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#activity-18"><i class="fa fa-check"></i><b>6.3.1</b> Activity</a></li>
<li class="chapter" data-level="6.3.2" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#answer-21"><i class="fa fa-check"></i><b>6.3.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#checking-for-normally-distributed-residuals"><i class="fa fa-check"></i><b>6.4</b> Checking for normally distributed residuals</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#base-r-histogram"><i class="fa fa-check"></i><b>6.4.1</b> Base R histogram</a></li>
<li class="chapter" data-level="6.4.2" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#quantile-comparison-plot"><i class="fa fa-check"></i><b>6.4.2</b> Quantile-comparison plot</a></li>
<li class="chapter" data-level="6.4.3" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#statistical-test-of-normality"><i class="fa fa-check"></i><b>6.4.3</b> Statistical test of normality</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#checking-constant-residual-variance"><i class="fa fa-check"></i><b>6.5</b> Checking constant residual variance</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#activity-20"><i class="fa fa-check"></i><b>6.5.1</b> Activity</a></li>
<li class="chapter" data-level="6.5.2" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#answer-23"><i class="fa fa-check"></i><b>6.5.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#checking-for-relationships-between-residuals-and-predicted-outcome-or-predictors"><i class="fa fa-check"></i><b>6.6</b> Checking for relationships between residuals and predicted outcome or predictors</a></li>
<li class="chapter" data-level="6.7" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#checking-linearity"><i class="fa fa-check"></i><b>6.7</b> Checking linearity</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#what-should-be-linear-in-a-linear-model"><i class="fa fa-check"></i><b>6.7.1</b> What should be linear in a linear model?</a></li>
<li class="chapter" data-level="6.7.2" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#checking-for-linearity"><i class="fa fa-check"></i><b>6.7.2</b> Checking for linearity</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#checking-influence-leave-one-out-analyses"><i class="fa fa-check"></i><b>6.8</b> Checking influence: leave-one-out analyses</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#residual-outliers"><i class="fa fa-check"></i><b>6.8.1</b> Residual outliers</a></li>
<li class="chapter" data-level="6.8.2" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#cooks-distance"><i class="fa fa-check"></i><b>6.8.2</b> Cook’s distance</a></li>
<li class="chapter" data-level="6.8.3" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#dfbeta-and-close-sibling-dfbetas"><i class="fa fa-check"></i><b>6.8.3</b> DFBETA and (close sibling) DFBETAS</a></li>
<li class="chapter" data-level="6.8.4" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#view-them-all"><i class="fa fa-check"></i><b>6.8.4</b> View them all</a></li>
<li class="chapter" data-level="6.8.5" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#so-er-what-should-we-do-with-potentially-influential-observations"><i class="fa fa-check"></i><b>6.8.5</b> So, er, what should we do with “potentially influential” observations…?</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#checking-the-variance-inflation-factors-vifs"><i class="fa fa-check"></i><b>6.9</b> Checking the variance inflation factors (VIFs)</a>
<ul>
<li class="chapter" data-level="6.9.1" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#activity-22"><i class="fa fa-check"></i><b>6.9.1</b> Activity</a></li>
<li class="chapter" data-level="6.9.2" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#answer-25"><i class="fa fa-check"></i><b>6.9.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#the-challenge"><i class="fa fa-check"></i><b>6.10</b> The challenge</a>
<ul>
<li class="chapter" data-level="6.10.1" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#activity-23"><i class="fa fa-check"></i><b>6.10.1</b> Activity</a></li>
<li class="chapter" data-level="6.10.2" data-path="linear-regression-diagnostics.html"><a href="linear-regression-diagnostics.html#answer-26"><i class="fa fa-check"></i><b>6.10.2</b> Answer</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html"><i class="fa fa-check"></i><b>7</b> Categorical predictors and interactions</a>
<ul>
<li class="chapter" data-level="7.1" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#before-we-begin-2"><i class="fa fa-check"></i><b>7.1</b> Before we begin</a></li>
<li class="chapter" data-level="7.2" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#the-dataset-2"><i class="fa fa-check"></i><b>7.2</b> The dataset</a></li>
<li class="chapter" data-level="7.3" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#factors"><i class="fa fa-check"></i><b>7.3</b> Factors</a></li>
<li class="chapter" data-level="7.4" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#visualising-the-data"><i class="fa fa-check"></i><b>7.4</b> Visualising the data</a></li>
<li class="chapter" data-level="7.5" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#the-punchline-occupation-type-does-predict-prestige"><i class="fa fa-check"></i><b>7.5</b> The punchline: occupation type does predict prestige</a></li>
<li class="chapter" data-level="7.6" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#understanding-factors-in-regression-models"><i class="fa fa-check"></i><b>7.6</b> Understanding factors in regression models</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#how-are-categorical-variables-encoded"><i class="fa fa-check"></i><b>7.6.1</b> How are categorical variables encoded?</a></li>
<li class="chapter" data-level="7.6.2" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#how-are-binary-two-level-categorical-predictors-encoded"><i class="fa fa-check"></i><b>7.6.2</b> How are binary (two-level) categorical predictors encoded?</a></li>
<li class="chapter" data-level="7.6.3" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#categorical-predictors-with-3-or-more-levels"><i class="fa fa-check"></i><b>7.6.3</b> Categorical predictors with 3 or more levels</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#interpreting-the-coefficients"><i class="fa fa-check"></i><b>7.7</b> Interpreting the coefficients</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#activity-25"><i class="fa fa-check"></i><b>7.7.1</b> Activity</a></li>
<li class="chapter" data-level="7.7.2" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#answer-28"><i class="fa fa-check"></i><b>7.7.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#checking-all-combinations"><i class="fa fa-check"></i><b>7.8</b> Checking all combinations</a></li>
<li class="chapter" data-level="7.9" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#the-intercept-is-not-always-the-mean-of-the-comparison-group"><i class="fa fa-check"></i><b>7.9</b> The intercept is not always the mean of the comparison group</a></li>
<li class="chapter" data-level="7.10" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#recap"><i class="fa fa-check"></i><b>7.10</b> Recap</a></li>
<li class="chapter" data-level="7.11" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#challenge"><i class="fa fa-check"></i><b>7.11</b> Challenge</a>
<ul>
<li class="chapter" data-level="7.11.1" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#activity-26"><i class="fa fa-check"></i><b>7.11.1</b> Activity</a></li>
<li class="chapter" data-level="7.11.2" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#answers-1"><i class="fa fa-check"></i><b>7.11.2</b> Answers</a></li>
</ul></li>
<li class="chapter" data-level="7.12" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#brief-introduction-to-interactions"><i class="fa fa-check"></i><b>7.12</b> Brief introduction to interactions</a>
<ul>
<li class="chapter" data-level="7.12.1" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#what-is-an-interaction"><i class="fa fa-check"></i><b>7.12.1</b> What is an interaction?</a></li>
<li class="chapter" data-level="7.12.2" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#how-to-test-for-interactions-in-r"><i class="fa fa-check"></i><b>7.12.2</b> How to test for interactions in R</a></li>
<li class="chapter" data-level="7.12.3" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#understanding-interactions"><i class="fa fa-check"></i><b>7.12.3</b> Understanding interactions</a></li>
<li class="chapter" data-level="7.12.4" data-path="categorical-predictors-and-interactions.html"><a href="categorical-predictors-and-interactions.html#further-reading-1"><i class="fa fa-check"></i><b>7.12.4</b> Further reading</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>8</b> Logistic regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="logistic-regression.html"><a href="logistic-regression.html#setup"><i class="fa fa-check"></i><b>8.1</b> Setup</a></li>
<li class="chapter" data-level="8.2" data-path="logistic-regression.html"><a href="logistic-regression.html#the-dataset-3"><i class="fa fa-check"></i><b>8.2</b> The dataset</a></li>
<li class="chapter" data-level="8.3" data-path="logistic-regression.html"><a href="logistic-regression.html#warmup-activity"><i class="fa fa-check"></i><b>8.3</b> Warmup activity</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="logistic-regression.html"><a href="logistic-regression.html#activity-27"><i class="fa fa-check"></i><b>8.3.1</b> Activity</a></li>
<li class="chapter" data-level="8.3.2" data-path="logistic-regression.html"><a href="logistic-regression.html#answer-29"><i class="fa fa-check"></i><b>8.3.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="logistic-regression.html"><a href="logistic-regression.html#the-punchline"><i class="fa fa-check"></i><b>8.4</b> The punchline</a></li>
<li class="chapter" data-level="8.5" data-path="logistic-regression.html"><a href="logistic-regression.html#intermezzo-parametric-versus-nonparametric"><i class="fa fa-check"></i><b>8.5</b> Intermezzo: parametric versus nonparametric</a></li>
<li class="chapter" data-level="8.6" data-path="logistic-regression.html"><a href="logistic-regression.html#glms"><i class="fa fa-check"></i><b>8.6</b> What is a generalised linear model?</a></li>
<li class="chapter" data-level="8.7" data-path="logistic-regression.html"><a href="logistic-regression.html#what-is-the-log-function-again"><i class="fa fa-check"></i><b>8.7</b> What is the log function again…?</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="logistic-regression.html"><a href="logistic-regression.html#log-arithmetic"><i class="fa fa-check"></i><b>8.7.1</b> The arithmetic</a></li>
<li class="chapter" data-level="8.7.2" data-path="logistic-regression.html"><a href="logistic-regression.html#why-log"><i class="fa fa-check"></i><b>8.7.2</b> Why log?</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="logistic-regression.html"><a href="logistic-regression.html#intercept-only-models-again"><i class="fa fa-check"></i><b>8.8</b> Intercept-only models again</a></li>
<li class="chapter" data-level="8.9" data-path="logistic-regression.html"><a href="logistic-regression.html#odds-and-log-odds"><i class="fa fa-check"></i><b>8.9</b> Odds and log odds</a></li>
<li class="chapter" data-level="8.10" data-path="logistic-regression.html"><a href="logistic-regression.html#back-to-that-intercept"><i class="fa fa-check"></i><b>8.10</b> Back to that intercept</a></li>
<li class="chapter" data-level="8.11" data-path="logistic-regression.html"><a href="logistic-regression.html#interpret-slopes"><i class="fa fa-check"></i><b>8.11</b> Interpreting model slopes</a>
<ul>
<li class="chapter" data-level="8.11.1" data-path="logistic-regression.html"><a href="logistic-regression.html#interpret-on-the-log-odds-scale"><i class="fa fa-check"></i><b>8.11.1</b> Interpret on the log-odds scale</a></li>
<li class="chapter" data-level="8.11.2" data-path="logistic-regression.html"><a href="logistic-regression.html#interpret-using-the-divide-by-4-approximation"><i class="fa fa-check"></i><b>8.11.2</b> Interpret using the “divide-by-4” approximation</a></li>
<li class="chapter" data-level="8.11.3" data-path="logistic-regression.html"><a href="logistic-regression.html#interpret-using-odds"><i class="fa fa-check"></i><b>8.11.3</b> Interpret using odds</a></li>
<li class="chapter" data-level="8.11.4" data-path="logistic-regression.html"><a href="logistic-regression.html#interpret-using-predicted-probabilities"><i class="fa fa-check"></i><b>8.11.4</b> Interpret using predicted probabilities</a></li>
</ul></li>
<li class="chapter" data-level="8.12" data-path="logistic-regression.html"><a href="logistic-regression.html#diagnostics"><i class="fa fa-check"></i><b>8.12</b> Diagnostics</a>
<ul>
<li class="chapter" data-level="8.12.1" data-path="logistic-regression.html"><a href="logistic-regression.html#check-the-residual-distribution"><i class="fa fa-check"></i><b>8.12.1</b> Check the residual distribution</a></li>
<li class="chapter" data-level="8.12.2" data-path="logistic-regression.html"><a href="logistic-regression.html#check-that-the-residual-mean-is-constant"><i class="fa fa-check"></i><b>8.12.2</b> Check that the residual mean is constant</a></li>
<li class="chapter" data-level="8.12.3" data-path="logistic-regression.html"><a href="logistic-regression.html#linearity-of-predictors"><i class="fa fa-check"></i><b>8.12.3</b> Linearity of predictors</a></li>
<li class="chapter" data-level="8.12.4" data-path="logistic-regression.html"><a href="logistic-regression.html#influence"><i class="fa fa-check"></i><b>8.12.4</b> Influence</a></li>
<li class="chapter" data-level="8.12.5" data-path="logistic-regression.html"><a href="logistic-regression.html#multicolinearity"><i class="fa fa-check"></i><b>8.12.5</b> Multicolinearity</a></li>
</ul></li>
<li class="chapter" data-level="8.13" data-path="logistic-regression.html"><a href="logistic-regression.html#a-challenge"><i class="fa fa-check"></i><b>8.13</b> A challenge</a>
<ul>
<li class="chapter" data-level="8.13.1" data-path="logistic-regression.html"><a href="logistic-regression.html#activity-31"><i class="fa fa-check"></i><b>8.13.1</b> Activity</a></li>
<li class="chapter" data-level="8.13.2" data-path="logistic-regression.html"><a href="logistic-regression.html#an-answer"><i class="fa fa-check"></i><b>8.13.2</b> (An) Answer</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="complex-surveys.html"><a href="complex-surveys.html"><i class="fa fa-check"></i><b>9</b> Complex surveys</a>
<ul>
<li class="chapter" data-level="9.1" data-path="complex-surveys.html"><a href="complex-surveys.html#readings"><i class="fa fa-check"></i><b>9.1</b> Readings</a></li>
<li class="chapter" data-level="9.2" data-path="complex-surveys.html"><a href="complex-surveys.html#the-dataset-4"><i class="fa fa-check"></i><b>9.2</b> The dataset</a></li>
<li class="chapter" data-level="9.3" data-path="complex-surveys.html"><a href="complex-surveys.html#the-components-of-a-survey-design"><i class="fa fa-check"></i><b>9.3</b> The components of a survey design</a></li>
<li class="chapter" data-level="9.4" data-path="complex-surveys.html"><a href="complex-surveys.html#describing-the-data"><i class="fa fa-check"></i><b>9.4</b> Describing the data</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="complex-surveys.html"><a href="complex-surveys.html#activity-32"><i class="fa fa-check"></i><b>9.4.1</b> Activity</a></li>
<li class="chapter" data-level="9.4.2" data-path="complex-surveys.html"><a href="complex-surveys.html#answer-33"><i class="fa fa-check"></i><b>9.4.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="complex-surveys.html"><a href="complex-surveys.html#fitting-a-glm"><i class="fa fa-check"></i><b>9.5</b> Fitting a GLM</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="complex-surveys.html"><a href="complex-surveys.html#activity-33"><i class="fa fa-check"></i><b>9.5.1</b> Activity</a></li>
<li class="chapter" data-level="9.5.2" data-path="complex-surveys.html"><a href="complex-surveys.html#answer-34"><i class="fa fa-check"></i><b>9.5.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="complex-surveys.html"><a href="complex-surveys.html#slopes"><i class="fa fa-check"></i><b>9.6</b> Slopes</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="complex-surveys.html"><a href="complex-surveys.html#activity-34"><i class="fa fa-check"></i><b>9.6.1</b> Activity</a></li>
<li class="chapter" data-level="9.6.2" data-path="complex-surveys.html"><a href="complex-surveys.html#answer-35"><i class="fa fa-check"></i><b>9.6.2</b> Answer</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="complex-surveys.html"><a href="complex-surveys.html#diagnostics-1"><i class="fa fa-check"></i><b>9.7</b> Diagnostics</a></li>
<li class="chapter" data-level="9.8" data-path="complex-surveys.html"><a href="complex-surveys.html#another-worked-example-the-european-social-survey"><i class="fa fa-check"></i><b>9.8</b> Another worked example: the European Social Survey</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="complex-surveys.html"><a href="complex-surveys.html#set-up-the-survey-object"><i class="fa fa-check"></i><b>9.8.1</b> Set up the survey object</a></li>
<li class="chapter" data-level="9.8.2" data-path="complex-surveys.html"><a href="complex-surveys.html#try-the-analysis"><i class="fa fa-check"></i><b>9.8.2</b> Try the analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>10</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Using R for social research</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="categorical-predictors-and-interactions" class="section level1" number="7">
<h1><span class="header-section-number">Chapter 7</span> Categorical predictors and interactions</h1>
<p>By the end of this chapter you will:</p>
<ul>
<li>Understand how to use R <em>factors</em>, which automatically deal with fiddly aspects of using categorical predictors in statistical models.</li>
<li>Be able to relate R output to what is going on behind the scenes, i.e., coding of a category with <span class="math inline">\(n\)</span>-levels in terms of <span class="math inline">\(n-1\)</span> binary 0/1 predictors.</li>
<li>See how R does interactions effects (the <code>*</code> and <code>:</code> operators).</li>
</ul>
<p>The lovely thing about the topics covered in this chapter is that they all transfer to every other model, e.g., logistic regression and other generalised linear models, multilevel models, and a huge number of models which you may encounter in future.</p>
<div id="before-we-begin-2" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Before we begin</h2>
<p>We are going to persist with the prestige dataset another time. (Last chapter, promise.) You could continue on the end of last week’s Markdown file or make a new one.</p>
<p>Ensure these handy packages are installed (you will only have to do that once) and included:</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="categorical-predictors-and-interactions.html#cb343-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb343-2"><a href="categorical-predictors-and-interactions.html#cb343-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
</div>
<div id="the-dataset-2" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> The dataset</h2>
<p>For ease of reference. Each row describes an occupation and aggregated data about that occupation (in 1970s Canada).</p>
<table>
<colgroup>
<col width="53%" />
<col width="46%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable name</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>occ</td>
<td>Occupation</td>
</tr>
<tr class="even">
<td>education</td>
<td>Average years of education for people in the job</td>
</tr>
<tr class="odd">
<td>income</td>
<td>Average income in dollars</td>
</tr>
<tr class="even">
<td>women</td>
<td>Percentage of women in occupation</td>
</tr>
<tr class="odd">
<td>prestige</td>
<td>A Pineo-Porter prestige score for the occupation with a possible range of 0-100 (higher = more prestigious)</td>
</tr>
<tr class="even">
<td>type</td>
<td>“bc” = blue collar <br> “wc” = white collar <br> “prof” = professional, managerial, or technical</td>
</tr>
</tbody>
</table>
<p>Read it in:</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="categorical-predictors-and-interactions.html#cb344-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;prestige.csv&quot;</span>)</span></code></pre></div>
<p>This week we will explore whether there are mean differences in prestige between the three types of profession: blue collar, white collar, and professional.</p>
</div>
<div id="factors" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Factors</h2>
<p>R has a special kind of object called a <em>factor</em> for representing categorical variables in statistical models. Ensure that R “knows” that you want to treat <code>type</code> as a factor by doing the following:</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="categorical-predictors-and-interactions.html#cb345-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>type <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>type)</span></code></pre></div>
<p>You can check whether a variable is a factor by doing:</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="categorical-predictors-and-interactions.html#cb346-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(dat<span class="sc">$</span>type)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Here’s a variable that isn’t:</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="categorical-predictors-and-interactions.html#cb348-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(dat<span class="sc">$</span>prestige)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>It’s numeric…</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="categorical-predictors-and-interactions.html#cb350-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.numeric</span>(dat<span class="sc">$</span>prestige)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>You can also look up the “class” of a variable:</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="categorical-predictors-and-interactions.html#cb352-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(dat<span class="sc">$</span>type)</span></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>You can check the levels of a factor by using the <code>levels</code> function:</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="categorical-predictors-and-interactions.html#cb354-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(dat<span class="sc">$</span>type)</span></code></pre></div>
<pre><code>## [1] &quot;bc&quot;   &quot;prof&quot; &quot;wc&quot;</code></pre>
<p>The order is alphabetical by default and can easily be changed.</p>
<p>The <code>levels</code> function only works for factors:</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="categorical-predictors-and-interactions.html#cb356-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(dat<span class="sc">$</span>prestige)</span></code></pre></div>
<pre><code>## NULL</code></pre>
</div>
<div id="visualising-the-data" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> Visualising the data</h2>
<p>(I go through this in some detail, for information. Feel free to skip over it on first reading.)</p>
<p>We will be exploring whether there are differences in a continuous variable (<code>prestige</code>) between levels of a categorical variable (<code>type</code>).</p>
<p>A traditional visualisation for this genre of comparison is the bar plot, with either standard error of the mean (SE mean) or standard deviation (SD) error bars.</p>
<p>These days, the recommendation is to look at the raw data before reducing it to means, for instance with a jitter plot.</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="categorical-predictors-and-interactions.html#cb358-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>) <span class="co"># Optional</span></span>
<span id="cb358-2"><a href="categorical-predictors-and-interactions.html#cb358-2" aria-hidden="true" tabindex="-1"></a>dat <span class="sc">%&gt;%</span></span>
<span id="cb358-3"><a href="categorical-predictors-and-interactions.html#cb358-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(type, prestige, <span class="at">colour =</span> type)) <span class="sc">+</span></span>
<span id="cb358-4"><a href="categorical-predictors-and-interactions.html#cb358-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="dv">0</span>,</span>
<span id="cb358-5"><a href="categorical-predictors-and-interactions.html#cb358-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">width =</span> .<span class="dv">1</span>,</span>
<span id="cb358-6"><a href="categorical-predictors-and-interactions.html#cb358-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb358-7"><a href="categorical-predictors-and-interactions.html#cb358-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">100</span>)</span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-246-1.png" width="288" /></p>
<p>We can see 4 observations in an “NA” category. Those are missing data, i.e., values in the dataset which have not been assigned a type.</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="categorical-predictors-and-interactions.html#cb359-1" aria-hidden="true" tabindex="-1"></a>dat <span class="sc">%&gt;%</span></span>
<span id="cb359-2"><a href="categorical-predictors-and-interactions.html#cb359-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(type))</span></code></pre></div>
<pre><code>##           occ education income women prestige type
## 1    athletes     11.44   8206  8.13     54.1 &lt;NA&gt;
## 2    newsboys      9.62    918  7.00     14.8 &lt;NA&gt;
## 3 babysitters      9.46    611 96.53     25.9 &lt;NA&gt;
## 4     farmers      6.84   3643  3.60     44.1 &lt;NA&gt;</code></pre>
<p>Also note that I have fixed the y-axis scale so that it covers the theoretical range of the prestige measure (0-100) rather than only the values present in the data.</p>
<p>Here is how to make the traditional bar plot. First calculate the means and standard error of the means for each group. The standard error is calculated as</p>
<p><span class="math display">\[
\frac{\mathit{SD}}{\sqrt{N}}
\]</span>
where <span class="math inline">\(N\)</span> is the number of observations. R has a function called <code>sqrt</code> for calculating the square root:</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="categorical-predictors-and-interactions.html#cb361-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>We use <code>group_by</code> as before to ask tidyverse to group observations by <code>type</code> of occupation, and then summarise the data. The <code>n</code> function simply counts the number of observations, which will also be calculated per group following the <code>group_by</code>.</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="categorical-predictors-and-interactions.html#cb363-1" aria-hidden="true" tabindex="-1"></a>dat_means <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb363-2"><a href="categorical-predictors-and-interactions.html#cb363-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(type) <span class="sc">%&gt;%</span></span>
<span id="cb363-3"><a href="categorical-predictors-and-interactions.html#cb363-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(prestige),</span>
<span id="cb363-4"><a href="categorical-predictors-and-interactions.html#cb363-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">SD   =</span> <span class="fu">sd</span>(prestige),</span>
<span id="cb363-5"><a href="categorical-predictors-and-interactions.html#cb363-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">SE   =</span> SD<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>()),</span>
<span id="cb363-6"><a href="categorical-predictors-and-interactions.html#cb363-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">n    =</span> <span class="fu">n</span>())</span>
<span id="cb363-7"><a href="categorical-predictors-and-interactions.html#cb363-7" aria-hidden="true" tabindex="-1"></a>dat_means</span></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   type   mean    SD    SE     n
##   &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 bc     35.5 10.0   1.51    44
## 2 prof   67.8  8.68  1.56    31
## 3 wc     42.2  9.52  1.98    23
## 4 &lt;NA&gt;   34.7 17.7   8.84     4</code></pre>
<p>Here is how I went about plotting these values.</p>
<p>I began by plotting the means:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="categorical-predictors-and-interactions.html#cb365-1" aria-hidden="true" tabindex="-1"></a>dat_means <span class="sc">%&gt;%</span></span>
<span id="cb365-2"><a href="categorical-predictors-and-interactions.html#cb365-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(type, mean)) <span class="sc">+</span></span>
<span id="cb365-3"><a href="categorical-predictors-and-interactions.html#cb365-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>)</span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-250-1.png" width="672" /></p>
<p>Then I added error bars:</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="categorical-predictors-and-interactions.html#cb366-1" aria-hidden="true" tabindex="-1"></a>dat_means <span class="sc">%&gt;%</span></span>
<span id="cb366-2"><a href="categorical-predictors-and-interactions.html#cb366-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(type, mean)) <span class="sc">+</span></span>
<span id="cb366-3"><a href="categorical-predictors-and-interactions.html#cb366-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb366-4"><a href="categorical-predictors-and-interactions.html#cb366-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean <span class="sc">-</span> SE,</span>
<span id="cb366-5"><a href="categorical-predictors-and-interactions.html#cb366-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> mean <span class="sc">+</span> SE))</span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-251-1.png" width="672" /></p>
<p>Following this, I fiddled around for fifteen minutes, wishing I had just looked up a bar plot I had made previously… (The lesson here is, build a stash of example R code you can quickly find, adapt, and reuse.)</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="categorical-predictors-and-interactions.html#cb367-1" aria-hidden="true" tabindex="-1"></a>dat_means <span class="sc">%&gt;%</span></span>
<span id="cb367-2"><a href="categorical-predictors-and-interactions.html#cb367-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(type)) <span class="sc">%&gt;%</span></span>
<span id="cb367-3"><a href="categorical-predictors-and-interactions.html#cb367-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(type, mean, <span class="at">fill =</span> type)) <span class="sc">+</span></span>
<span id="cb367-4"><a href="categorical-predictors-and-interactions.html#cb367-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">show.legend =</span> F) <span class="sc">+</span></span>
<span id="cb367-5"><a href="categorical-predictors-and-interactions.html#cb367-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean <span class="sc">-</span> SE,</span>
<span id="cb367-6"><a href="categorical-predictors-and-interactions.html#cb367-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> mean <span class="sc">+</span> SE), <span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb367-7"><a href="categorical-predictors-and-interactions.html#cb367-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Occupation type&quot;</span>) <span class="sc">+</span></span>
<span id="cb367-8"><a href="categorical-predictors-and-interactions.html#cb367-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Mean prestige&quot;</span>) <span class="sc">+</span></span>
<span id="cb367-9"><a href="categorical-predictors-and-interactions.html#cb367-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb367-10"><a href="categorical-predictors-and-interactions.html#cb367-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() </span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-252-1.png" width="288" /></p>
<p>You might want to add standard deviation bars instead:</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="categorical-predictors-and-interactions.html#cb368-1" aria-hidden="true" tabindex="-1"></a>dat_means <span class="sc">%&gt;%</span></span>
<span id="cb368-2"><a href="categorical-predictors-and-interactions.html#cb368-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(type)) <span class="sc">%&gt;%</span></span>
<span id="cb368-3"><a href="categorical-predictors-and-interactions.html#cb368-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(type, mean, <span class="at">fill =</span> type)) <span class="sc">+</span></span>
<span id="cb368-4"><a href="categorical-predictors-and-interactions.html#cb368-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">show.legend =</span> F) <span class="sc">+</span></span>
<span id="cb368-5"><a href="categorical-predictors-and-interactions.html#cb368-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean <span class="sc">-</span> SD,</span>
<span id="cb368-6"><a href="categorical-predictors-and-interactions.html#cb368-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> mean <span class="sc">+</span> SD), <span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb368-7"><a href="categorical-predictors-and-interactions.html#cb368-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Occupation type&quot;</span>) <span class="sc">+</span></span>
<span id="cb368-8"><a href="categorical-predictors-and-interactions.html#cb368-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Mean prestige&quot;</span>) <span class="sc">+</span></span>
<span id="cb368-9"><a href="categorical-predictors-and-interactions.html#cb368-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">100</span>) <span class="sc">+</span> </span>
<span id="cb368-10"><a href="categorical-predictors-and-interactions.html#cb368-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() </span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-253-1.png" width="288" /></p>
<p>You might also want less vibrant colours, e.g., if you wish to include the graph in a publication:</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="categorical-predictors-and-interactions.html#cb369-1" aria-hidden="true" tabindex="-1"></a>dat_means <span class="sc">%&gt;%</span></span>
<span id="cb369-2"><a href="categorical-predictors-and-interactions.html#cb369-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(type)) <span class="sc">%&gt;%</span></span>
<span id="cb369-3"><a href="categorical-predictors-and-interactions.html#cb369-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(type, mean)) <span class="sc">+</span></span>
<span id="cb369-4"><a href="categorical-predictors-and-interactions.html#cb369-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey&quot;</span>) <span class="sc">+</span></span>
<span id="cb369-5"><a href="categorical-predictors-and-interactions.html#cb369-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean <span class="sc">-</span> SD,</span>
<span id="cb369-6"><a href="categorical-predictors-and-interactions.html#cb369-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> mean <span class="sc">+</span> SD), <span class="at">width =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb369-7"><a href="categorical-predictors-and-interactions.html#cb369-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Occupation type&quot;</span>) <span class="sc">+</span></span>
<span id="cb369-8"><a href="categorical-predictors-and-interactions.html#cb369-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Mean prestige&quot;</span>) <span class="sc">+</span></span>
<span id="cb369-9"><a href="categorical-predictors-and-interactions.html#cb369-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb369-10"><a href="categorical-predictors-and-interactions.html#cb369-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() </span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-254-1.png" width="288" /></p>
<p>These are the chunk options I used to change the dimensions of the figure, which might be handy to know about too (they go at the top of the chunk):</p>
<pre><code>{r fig.height=3, fig.width=3}</code></pre>
</div>
<div id="the-punchline-occupation-type-does-predict-prestige" class="section level2" number="7.5">
<h2><span class="header-section-number">7.5</span> The punchline: occupation type does predict prestige</h2>
<p>This is where we are heading.</p>
<p>First, select the variables you want to model and remove missing values:</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="categorical-predictors-and-interactions.html#cb371-1" aria-hidden="true" tabindex="-1"></a>dat_no_NAs <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb371-2"><a href="categorical-predictors-and-interactions.html#cb371-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(occ, prestige, type) <span class="sc">%&gt;%</span></span>
<span id="cb371-3"><a href="categorical-predictors-and-interactions.html#cb371-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code></pre></div>
<p>We could just have removed missing variables from the whole dataset – it would have worked for the prestige dataset since there are only four missing values and they are all in one variable. However, for larger datasets doing so might easily wipe out everything! For more on handling missing data correctly, try the book by van Buuren (2018).</p>
<p>Now, fit an intercept-only model and compare it with a model which has <code>type</code> as a predictor. R will automatically do something sensible with <code>type</code> since it knows that it is a factor.</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="categorical-predictors-and-interactions.html#cb372-1" aria-hidden="true" tabindex="-1"></a>intercept_only <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> dat_no_NAs)</span>
<span id="cb372-2"><a href="categorical-predictors-and-interactions.html#cb372-2" aria-hidden="true" tabindex="-1"></a>type_mod       <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> type, <span class="at">data =</span> dat_no_NAs)</span>
<span id="cb372-3"><a href="categorical-predictors-and-interactions.html#cb372-3" aria-hidden="true" tabindex="-1"></a>                             <span class="co"># (the 1 is implicit)</span></span>
<span id="cb372-4"><a href="categorical-predictors-and-interactions.html#cb372-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb372-5"><a href="categorical-predictors-and-interactions.html#cb372-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(intercept_only, type_mod)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: prestige ~ 1
## Model 2: prestige ~ type
##   Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1     97 28346.9                                  
## 2     95  8571.3  2     19776 109.59 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Occupation type does indeed explain variation in prestige, <span class="math inline">\(F(2,95) = 109.59\)</span>, <span class="math inline">\(p &lt; .001\)</span>.</p>
<p>An even easier way to do this is using <code>car</code>’s <code>Anova</code> command (uppercase <em>A</em>). This does not require you to fit an intercept-only model yourself and deals with multiple predictors (handy later):</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="categorical-predictors-and-interactions.html#cb374-1" aria-hidden="true" tabindex="-1"></a>type_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> type, <span class="at">data =</span> dat_no_NAs)</span>
<span id="cb374-2"><a href="categorical-predictors-and-interactions.html#cb374-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(type_mod)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: prestige
##            Sum Sq Df F value    Pr(&gt;F)    
## type      19775.6  2  109.59 &lt; 2.2e-16 ***
## Residuals  8571.3 95                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Read on to see why this has worked and also to work out which of the three occupations differ from each other in prestige…</p>
</div>
<div id="understanding-factors-in-regression-models" class="section level2" number="7.6">
<h2><span class="header-section-number">7.6</span> Understanding factors in regression models</h2>
<div id="how-are-categorical-variables-encoded" class="section level3 tabset" number="7.6.1">
<h3><span class="header-section-number">7.6.1</span> How are categorical variables encoded?</h3>
<p>Let’s begin with an easier example with only two groups: blue collar and white collar occupations:</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="categorical-predictors-and-interactions.html#cb376-1" aria-hidden="true" tabindex="-1"></a>just_two <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb376-2"><a href="categorical-predictors-and-interactions.html#cb376-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(type <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;bc&quot;</span>,<span class="st">&quot;wc&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb376-3"><a href="categorical-predictors-and-interactions.html#cb376-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(occ, prestige, type)</span></code></pre></div>
<p>Here are the means of prestige for both groups:</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="categorical-predictors-and-interactions.html#cb377-1" aria-hidden="true" tabindex="-1"></a>just_two <span class="sc">%&gt;%</span></span>
<span id="cb377-2"><a href="categorical-predictors-and-interactions.html#cb377-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(type) <span class="sc">%&gt;%</span></span>
<span id="cb377-3"><a href="categorical-predictors-and-interactions.html#cb377-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_prestige =</span> <span class="fu">mean</span>(prestige))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   type  mean_prestige
##   &lt;fct&gt;         &lt;dbl&gt;
## 1 bc             35.5
## 2 wc             42.2</code></pre>
<p>Next, let’s fit a regression model, predicting prestige from occupation type:</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="categorical-predictors-and-interactions.html#cb379-1" aria-hidden="true" tabindex="-1"></a>easier <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> type, <span class="at">data =</span> just_two)</span>
<span id="cb379-2"><a href="categorical-predictors-and-interactions.html#cb379-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(easier)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ type, data = just_two)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.2273  -7.0273  -0.2273   6.8227  25.2565 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   35.527      1.486  23.914   &lt;2e-16 ***
## typewc         6.716      2.536   2.649   0.0101 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.855 on 65 degrees of freedom
## Multiple R-squared:  0.09742,    Adjusted R-squared:  0.08353 
## F-statistic: 7.016 on 1 and 65 DF,  p-value: 0.01013</code></pre>
<p>Note how we told <code>lm</code> that the predictor is <code>type</code>; however, the summary is displaying a slope for <code>typewc</code>. Curious…</p>
<div id="activity-24" class="section level4" number="7.6.1.1">
<h4><span class="header-section-number">7.6.1.1</span> Activity</h4>
<p>Examine the estimates (the intercept and the slope for <code>typewc</code>) in this model and compare them with the means of the two groups. Can you see where the numbers come from?</p>
</div>
<div id="answer-27" class="section level4" number="7.6.1.2">
<h4><span class="header-section-number">7.6.1.2</span> Answer</h4>
<p>The intercept is the same as the mean prestige for <code>bc</code> (<span class="math inline">\(35.527\)</span>) and the slope for <code>typewc</code> is equal to the mean <em>difference</em> in prestige between the two groups: white collar minus blue collar (<span class="math inline">\(42.243 - 35.527 = 6.716\)</span>).</p>
</div>
</div>
<div id="how-are-binary-two-level-categorical-predictors-encoded" class="section level3" number="7.6.2">
<h3><span class="header-section-number">7.6.2</span> How are binary (two-level) categorical predictors encoded?</h3>
<p><strong>First let me emphasise that you do not need to do this coding yourself; this section aims to demonstrate how the coding works, not how to carry out an analysis.</strong></p>
<p>When you have a binary categorical variable (one with two levels), one level is coded as 0 and the other as 1. By default, R chooses alphabetically.</p>
<p>Here is something equivalent – a “hand coded” variable which is 1 for white collar occupations and 0 for blue collar:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="categorical-predictors-and-interactions.html#cb381-1" aria-hidden="true" tabindex="-1"></a>just_two<span class="sc">$</span>type_wc <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(just_two<span class="sc">$</span>type <span class="sc">==</span> <span class="st">&quot;wc&quot;</span>)</span></code></pre></div>
<p>Have a look, comparing the <code>type</code> column with <code>type_wc</code>:</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="categorical-predictors-and-interactions.html#cb382-1" aria-hidden="true" tabindex="-1"></a>just_two</span></code></pre></div>
<pre><code>##                          occ prestige type type_wc
## 1              nursing aides     34.9   bc       0
## 2        medical technicians     67.5   wc       1
## 3        radio tv announcers     57.6   wc       1
## 4                secretaries     46.0   wc       1
## 5                    typists     41.9   wc       1
## 6                bookkeepers     49.4   wc       1
## 7           tellers cashiers     42.3   wc       1
## 8         computer operators     47.7   wc       1
## 9            shipping clerks     30.9   wc       1
## 10               file clerks     32.7   wc       1
## 11              receptionsts     38.7   wc       1
## 12             mail carriers     36.1   wc       1
## 13             postal clerks     37.2   wc       1
## 14       telephone operators     38.1   wc       1
## 15                collectors     29.4   wc       1
## 16           claim adjustors     51.1   wc       1
## 17             travel clerks     35.7   wc       1
## 18             office clerks     35.6   wc       1
## 19         sales supervisors     41.5   wc       1
## 20     commercial travellers     40.2   wc       1
## 21              sales clerks     26.5   wc       1
## 22 service station attendant     23.3   bc       0
## 23          insurance agents     47.3   wc       1
## 24      real estate salesmen     47.1   wc       1
## 25                    buyers     51.1   wc       1
## 26              firefighters     43.5   bc       0
## 27                 policemen     51.6   bc       0
## 28                     cooks     29.7   bc       0
## 29                bartenders     20.2   bc       0
## 30         funeral directors     54.9   bc       0
## 31                launderers     20.8   bc       0
## 32                  janitors     17.3   bc       0
## 33        elevator operators     20.1   bc       0
## 34              farm workers     21.5   bc       0
## 35      rotary well drillers     35.3   bc       0
## 36                    bakers     38.9   bc       0
## 37            slaughterers 1     25.2   bc       0
## 38            slaughterers 2     34.8   bc       0
## 39                   canners     23.2   bc       0
## 40           textile weavers     33.3   bc       0
## 41         textile labourers     28.8   bc       0
## 42           tool die makers     42.5   bc       0
## 43                machinists     44.2   bc       0
## 44       sheet metal workers     35.9   bc       0
## 45                   welders     41.8   bc       0
## 46              auto workers     35.9   bc       0
## 47          aircraft workers     43.7   bc       0
## 48        electronic workers     50.8   bc       0
## 49        radio tv repairmen     37.2   bc       0
## 50     sewing mach operators     28.2   bc       0
## 51            auto repairmen     38.1   bc       0
## 52        aircraft repairmen     50.3   bc       0
## 53        railway sectionmen     27.3   bc       0
## 54        electrical linemen     40.9   bc       0
## 55              electricians     50.2   bc       0
## 56      construction foremen     51.1   bc       0
## 57                carpenters     38.9   bc       0
## 58                    masons     36.2   bc       0
## 59            house painters     29.9   bc       0
## 60                  plumbers     42.9   bc       0
## 61    construction labourers     26.5   bc       0
## 62           train engineers     48.9   bc       0
## 63               bus drivers     35.9   bc       0
## 64              taxi drivers     25.1   bc       0
## 65              longshoremen     26.1   bc       0
## 66               typesetters     42.2   bc       0
## 67               bookbinders     35.2   bc       0</code></pre>
<p>Now let’s fit a regression model with this binary 0/1 variable as a predictor:</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="categorical-predictors-and-interactions.html#cb384-1" aria-hidden="true" tabindex="-1"></a>the_binary <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> type_wc, <span class="at">data =</span> just_two)</span>
<span id="cb384-2"><a href="categorical-predictors-and-interactions.html#cb384-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(the_binary)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ type_wc, data = just_two)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.2273  -7.0273  -0.2273   6.8227  25.2565 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   35.527      1.486  23.914   &lt;2e-16 ***
## type_wc        6.716      2.536   2.649   0.0101 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.855 on 65 degrees of freedom
## Multiple R-squared:  0.09742,    Adjusted R-squared:  0.08353 
## F-statistic: 7.016 on 1 and 65 DF,  p-value: 0.01013</code></pre>
<p>Again, the intercept provides the mean prestige for blue collar and the slope for <code>type_wc</code> gives the mean <em>difference</em> between blue collar and white collar. This model is mathematically identical to the one that R built using the factor variable.</p>
<p>A (slightly jittered) picture might help you see why this is.</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="categorical-predictors-and-interactions.html#cb386-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">45</span>)</span>
<span id="cb386-2"><a href="categorical-predictors-and-interactions.html#cb386-2" aria-hidden="true" tabindex="-1"></a>just_two <span class="sc">%&gt;%</span></span>
<span id="cb386-3"><a href="categorical-predictors-and-interactions.html#cb386-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(type_wc,prestige)) <span class="sc">+</span></span>
<span id="cb386-4"><a href="categorical-predictors-and-interactions.html#cb386-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> .<span class="dv">02</span>, <span class="at">height =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb386-5"><a href="categorical-predictors-and-interactions.html#cb386-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">coef</span>(the_binary)[<span class="dv">1</span>],</span>
<span id="cb386-6"><a href="categorical-predictors-and-interactions.html#cb386-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope     =</span> <span class="fu">coef</span>(the_binary)[<span class="dv">2</span>])</span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-264-1.png" width="672" /></p>
<p>The values at the left hand side, above 0, are for blue collar occupations and at the right hand size, above 1, are for white collar occupations.</p>
<p>We asked <code>lm</code> to estimate an intercept (<span class="math inline">\(\beta_0\)</span>) and slope for <code>type_wc</code> (<span class="math inline">\(\beta_1\)</span>).</p>
<p><span class="math display">\[
\mathtt{prestige} = \beta_0 + \beta_1 \times \mathtt{type\_wc}
\]</span></p>
<p>This is what it found:</p>
<p><span class="math display">\[
\mathtt{prestige} = 35.5  + 6.7 \times \mathtt{type\_wc}
\]</span></p>
<p>Interpret the regression model as usual: for every unit increase in <code>type_wc</code>, prestige increases by 6.7. That’s the slope in the picture above.</p>
<p>But the <code>type_wc</code> variable only has two possible values, so this is the simplest example of “unit increase.” It can be 1, in which case we get the mean of white collar:</p>
<p><span class="math display">\[
\begin{array}{rcl}
\mathtt{prestige} &amp; = &amp;  35.5  + 6.7 \times \mathtt{type\_wc}\\
                  &amp; = &amp;  35.5  + 6.7 \times 1 \\
                  &amp; = &amp;  35.5  + 6.7 \\   
                  &amp; = &amp;  42.2  
\end{array}
\]</span></p>
<p>Alternatively, the predictor can be zero, in which case we get the mean of blue collar:</p>
<p><span class="math display">\[
\begin{array}{rcl}
\mathtt{prestige} &amp; = &amp;  35.5  + 6.7 \times \mathtt{type\_wc}\\
                  &amp; = &amp;  35.5  + 6.7 \times 0 \\
                  &amp; = &amp;  35.5  + 0 \\   
                  &amp; = &amp;  35.5
\end{array}
\]</span></p>
<p>By the way, this is equivalent to a two-sample t-test assuming equal variance:</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="categorical-predictors-and-interactions.html#cb387-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(prestige <span class="sc">~</span> type, <span class="at">data =</span> just_two, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  prestige by type
## t = -2.6487, df = 65, p-value = 0.01013
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -11.780279  -1.652132
## sample estimates:
## mean in group bc mean in group wc 
##         35.52727         42.24348</code></pre>
</div>
<div id="categorical-predictors-with-3-or-more-levels" class="section level3" number="7.6.3">
<h3><span class="header-section-number">7.6.3</span> Categorical predictors with 3 or more levels</h3>
<p>In general, if a categorical variable has <span class="math inline">\(n\)</span> levels, then there will be <span class="math inline">\(n-1\)</span> binary predictors added to the regression model. One level must be chosen as the comparison level. Slopes for the predictors represent <em>differences</em> from that comparison level.</p>
<p>Here is a model, fitted using R’s automatic coding (and summarised with the aid of a pipe, just to add a little variation):</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="categorical-predictors-and-interactions.html#cb389-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(prestige <span class="sc">~</span> type, <span class="at">data =</span> dat_no_NAs) <span class="sc">%&gt;%</span></span>
<span id="cb389-2"><a href="categorical-predictors-and-interactions.html#cb389-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ type, data = dat_no_NAs)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.2273  -7.1773  -0.0854   6.1174  25.2565 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   35.527      1.432  24.810  &lt; 2e-16 ***
## typeprof      32.321      2.227  14.511  &lt; 2e-16 ***
## typewc         6.716      2.444   2.748  0.00718 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.499 on 95 degrees of freedom
## Multiple R-squared:  0.6976, Adjusted R-squared:  0.6913 
## F-statistic: 109.6 on 2 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now let’s do the same again “by hand,” to show the coding:</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="categorical-predictors-and-interactions.html#cb391-1" aria-hidden="true" tabindex="-1"></a>dat_no_NAs<span class="sc">$</span>type_prof <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(dat_no_NAs<span class="sc">$</span>type <span class="sc">==</span> <span class="st">&quot;prof&quot;</span>)</span>
<span id="cb391-2"><a href="categorical-predictors-and-interactions.html#cb391-2" aria-hidden="true" tabindex="-1"></a>dat_no_NAs<span class="sc">$</span>type_wc   <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(dat_no_NAs<span class="sc">$</span>type <span class="sc">==</span> <span class="st">&quot;wc&quot;</span>)</span></code></pre></div>
<p>There are now two predictors: <code>type_prof</code> is 1 when the occupation type is <code>prof</code> and 0 otherwise; <code>type_wc</code> is 1 when the occupation type is <code>wc</code> and 0 otherwise. Whenever the occupation type is <code>bc</code>, both of these predictors are zero.</p>
<p>Have a look to see what this has done, comparing the <code>type</code> column with <code>type_prof</code> and <code>type_wc</code>:</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="categorical-predictors-and-interactions.html#cb392-1" aria-hidden="true" tabindex="-1"></a>dat_no_NAs</span></code></pre></div>
<pre><code>##                           occ prestige type type_prof type_wc
## 1          gov administrators     68.8 prof         1       0
## 2            general managers     69.1 prof         1       0
## 3                 accountants     63.4 prof         1       0
## 4         purchasing officers     56.8 prof         1       0
## 5                    chemists     73.5 prof         1       0
## 6                  physicists     77.6 prof         1       0
## 7                  biologists     72.6 prof         1       0
## 8                  architects     78.1 prof         1       0
## 9             civil engineers     73.1 prof         1       0
## 10           mining engineers     68.8 prof         1       0
## 11                  surveyors     62.0 prof         1       0
## 12                draughtsmen     60.0 prof         1       0
## 13        computer programers     53.8 prof         1       0
## 14                 economists     62.2 prof         1       0
## 15              psychologists     74.9 prof         1       0
## 16             social workers     55.1 prof         1       0
## 17                    lawyers     82.3 prof         1       0
## 18                 librarians     58.1 prof         1       0
## 19     vocational counsellors     58.3 prof         1       0
## 20                  ministers     72.8 prof         1       0
## 21        university teachers     84.6 prof         1       0
## 22    primary school teachers     59.6 prof         1       0
## 23  secondary school teachers     66.1 prof         1       0
## 24                 physicians     87.2 prof         1       0
## 25              veterinarians     66.7 prof         1       0
## 26   osteopaths chiropractors     68.4 prof         1       0
## 27                     nurses     64.7 prof         1       0
## 28              nursing aides     34.9   bc         0       0
## 29           physio therapsts     72.1 prof         1       0
## 30                pharmacists     69.3 prof         1       0
## 31        medical technicians     67.5   wc         0       1
## 32         commercial artists     57.2 prof         1       0
## 33        radio tv announcers     57.6   wc         0       1
## 35                secretaries     46.0   wc         0       1
## 36                    typists     41.9   wc         0       1
## 37                bookkeepers     49.4   wc         0       1
## 38           tellers cashiers     42.3   wc         0       1
## 39         computer operators     47.7   wc         0       1
## 40            shipping clerks     30.9   wc         0       1
## 41                file clerks     32.7   wc         0       1
## 42               receptionsts     38.7   wc         0       1
## 43              mail carriers     36.1   wc         0       1
## 44              postal clerks     37.2   wc         0       1
## 45        telephone operators     38.1   wc         0       1
## 46                 collectors     29.4   wc         0       1
## 47            claim adjustors     51.1   wc         0       1
## 48              travel clerks     35.7   wc         0       1
## 49              office clerks     35.6   wc         0       1
## 50          sales supervisors     41.5   wc         0       1
## 51      commercial travellers     40.2   wc         0       1
## 52               sales clerks     26.5   wc         0       1
## 54  service station attendant     23.3   bc         0       0
## 55           insurance agents     47.3   wc         0       1
## 56       real estate salesmen     47.1   wc         0       1
## 57                     buyers     51.1   wc         0       1
## 58               firefighters     43.5   bc         0       0
## 59                  policemen     51.6   bc         0       0
## 60                      cooks     29.7   bc         0       0
## 61                 bartenders     20.2   bc         0       0
## 62          funeral directors     54.9   bc         0       0
## 64                 launderers     20.8   bc         0       0
## 65                   janitors     17.3   bc         0       0
## 66         elevator operators     20.1   bc         0       0
## 68               farm workers     21.5   bc         0       0
## 69       rotary well drillers     35.3   bc         0       0
## 70                     bakers     38.9   bc         0       0
## 71             slaughterers 1     25.2   bc         0       0
## 72             slaughterers 2     34.8   bc         0       0
## 73                    canners     23.2   bc         0       0
## 74            textile weavers     33.3   bc         0       0
## 75          textile labourers     28.8   bc         0       0
## 76            tool die makers     42.5   bc         0       0
## 77                 machinists     44.2   bc         0       0
## 78        sheet metal workers     35.9   bc         0       0
## 79                    welders     41.8   bc         0       0
## 80               auto workers     35.9   bc         0       0
## 81           aircraft workers     43.7   bc         0       0
## 82         electronic workers     50.8   bc         0       0
## 83         radio tv repairmen     37.2   bc         0       0
## 84      sewing mach operators     28.2   bc         0       0
## 85             auto repairmen     38.1   bc         0       0
## 86         aircraft repairmen     50.3   bc         0       0
## 87         railway sectionmen     27.3   bc         0       0
## 88         electrical linemen     40.9   bc         0       0
## 89               electricians     50.2   bc         0       0
## 90       construction foremen     51.1   bc         0       0
## 91                 carpenters     38.9   bc         0       0
## 92                     masons     36.2   bc         0       0
## 93             house painters     29.9   bc         0       0
## 94                   plumbers     42.9   bc         0       0
## 95     construction labourers     26.5   bc         0       0
## 96                     pilots     66.1 prof         1       0
## 97            train engineers     48.9   bc         0       0
## 98                bus drivers     35.9   bc         0       0
## 99               taxi drivers     25.1   bc         0       0
## 100              longshoremen     26.1   bc         0       0
## 101               typesetters     42.2   bc         0       0
## 102               bookbinders     35.2   bc         0       0</code></pre>
<p>If we fit a model with these two “hand coded” predictors, the results are identical to what R did automatically:</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="categorical-predictors-and-interactions.html#cb394-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(prestige <span class="sc">~</span> type_prof <span class="sc">+</span> type_wc, <span class="at">data =</span> dat_no_NAs) <span class="sc">%&gt;%</span></span>
<span id="cb394-2"><a href="categorical-predictors-and-interactions.html#cb394-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ type_prof + type_wc, data = dat_no_NAs)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.2273  -7.1773  -0.0854   6.1174  25.2565 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   35.527      1.432  24.810  &lt; 2e-16 ***
## type_prof     32.321      2.227  14.511  &lt; 2e-16 ***
## type_wc        6.716      2.444   2.748  0.00718 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.499 on 95 degrees of freedom
## Multiple R-squared:  0.6976, Adjusted R-squared:  0.6913 
## F-statistic: 109.6 on 2 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now the formula is:</p>
<p><span class="math display">\[
\begin{array}{rcl}
\mathtt{prestige} &amp; = &amp;  35.5  + 32.3 \times \mathtt{type\_prof} + 6.7 \times  \mathtt{type\_wc}
\end{array}
\]</span></p>
<p>There are three possibilities:</p>
<ul>
<li><code>type_prof</code> and <code>type_wc</code> are both zero, so the model computes the mean prestige for blue collar workers.</li>
</ul>
<p><span class="math display">\[
\begin{array}{rcl}
\mathtt{prestige} &amp; = &amp;  35.5  + 32.3 \times 0 + 6.7 \times  0\\
                  &amp; = &amp;  35.5
\end{array}
\]</span></p>
<ul>
<li><code>type_prof</code> is 1 and <code>type_wc</code> is 0, so the model computes the mean prestige for professionals.</li>
</ul>
<p><span class="math display">\[
\begin{array}{rcl}
\mathtt{prestige} &amp; = &amp;  35.5 + 32.3 \times 1 + 6.7 \times  0\\
                  &amp; = &amp;  35.5 + 32.3\\
                  &amp; = &amp;  67.8
\end{array}
\]</span></p>
<ul>
<li><code>type_prof</code> is 0 and <code>type_wc</code> is 1, so the model computes the mean prestige for white collar workers.</li>
</ul>
<p><span class="math display">\[
\begin{array}{rcl}
\mathtt{prestige} &amp; = &amp;  35.5 + 32.3 \times 0 + 6.7 \times  1\\
                  &amp; = &amp;  35.5 + 6.7\\
                  &amp; = &amp;  42.2 
\end{array}
\]</span></p>
</div>
</div>
<div id="interpreting-the-coefficients" class="section level2 tabset" number="7.7">
<h2><span class="header-section-number">7.7</span> Interpreting the coefficients</h2>
<p>Here’s the model again:</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="categorical-predictors-and-interactions.html#cb396-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(prestige <span class="sc">~</span> type, <span class="at">data =</span> dat_no_NAs) <span class="sc">%&gt;%</span></span>
<span id="cb396-2"><a href="categorical-predictors-and-interactions.html#cb396-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ type, data = dat_no_NAs)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.2273  -7.1773  -0.0854   6.1174  25.2565 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   35.527      1.432  24.810  &lt; 2e-16 ***
## typeprof      32.321      2.227  14.511  &lt; 2e-16 ***
## typewc         6.716      2.444   2.748  0.00718 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.499 on 95 degrees of freedom
## Multiple R-squared:  0.6976, Adjusted R-squared:  0.6913 
## F-statistic: 109.6 on 2 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>From this we can see that the prestige for professionals is 32.3 points more than for blue collar workers (<span class="math inline">\(t = 14.5\)</span>, <span class="math inline">\(p &lt; .001\)</span>) and prestige for white collar workers is 6.7 points more than for blue collar (<span class="math inline">\(t = 2.7\)</span>, <span class="math inline">\(p = .007\)</span>); both differences are statistically significant.</p>
<p>We have a variable with three levels and this has ended up the regression model as two predictors, (1) <code>typewc</code> and (2) <code>typeprof</code>, the slopes of which represent the <em>difference</em> between (1) <code>wc</code> and <code>bc</code> and (2) <code>prof</code> and <code>bc</code>, respectively.</p>
<p>But this does not currently show us all combinations. What is the difference between <code>wc</code> and <code>prof</code>?</p>
<p>Here is <code>relevel</code> to the rescue. It relevels a factor so that whichever level you name comes first. You can add the command directly to a model specification like this:</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="categorical-predictors-and-interactions.html#cb398-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(prestige <span class="sc">~</span> <span class="fu">relevel</span>(type, <span class="st">&quot;prof&quot;</span>), <span class="at">data =</span> dat_no_NAs) <span class="sc">%&gt;%</span></span>
<span id="cb398-2"><a href="categorical-predictors-and-interactions.html#cb398-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ relevel(type, &quot;prof&quot;), data = dat_no_NAs)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.2273  -7.1773  -0.0854   6.1174  25.2565 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               67.848      1.706  39.770  &lt; 2e-16 ***
## relevel(type, &quot;prof&quot;)bc  -32.321      2.227 -14.511  &lt; 2e-16 ***
## relevel(type, &quot;prof&quot;)wc  -25.605      2.614  -9.795 4.53e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.499 on 95 degrees of freedom
## Multiple R-squared:  0.6976, Adjusted R-squared:  0.6913 
## F-statistic: 109.6 on 2 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Or, do it a longer but clearer way, e.g.,</p>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="categorical-predictors-and-interactions.html#cb400-1" aria-hidden="true" tabindex="-1"></a>dat_no_NAs<span class="sc">$</span>type_vs_prof <span class="ot">&lt;-</span> <span class="fu">relevel</span>(dat_no_NAs<span class="sc">$</span>type, <span class="st">&quot;prof&quot;</span>)</span>
<span id="cb400-2"><a href="categorical-predictors-and-interactions.html#cb400-2" aria-hidden="true" tabindex="-1"></a>myMod <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> type_vs_prof, <span class="at">data =</span> dat_no_NAs)</span>
<span id="cb400-3"><a href="categorical-predictors-and-interactions.html#cb400-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(myMod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ type_vs_prof, data = dat_no_NAs)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.2273  -7.1773  -0.0854   6.1174  25.2565 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      67.848      1.706  39.770  &lt; 2e-16 ***
## type_vs_profbc  -32.321      2.227 -14.511  &lt; 2e-16 ***
## type_vs_profwc  -25.605      2.614  -9.795 4.53e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.499 on 95 degrees of freedom
## Multiple R-squared:  0.6976, Adjusted R-squared:  0.6913 
## F-statistic: 109.6 on 2 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The advantage of this is that we can have a look at the levels and check that <code>prof</code> comes first:</p>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="categorical-predictors-and-interactions.html#cb402-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(dat_no_NAs<span class="sc">$</span>type_vs_prof)</span></code></pre></div>
<pre><code>## [1] &quot;prof&quot; &quot;bc&quot;   &quot;wc&quot;</code></pre>
<div id="activity-25" class="section level3" number="7.7.1">
<h3><span class="header-section-number">7.7.1</span> Activity</h3>
<p>Interpret the coefficients in this <code>myMod</code> model.</p>
</div>
<div id="answer-28" class="section level3" number="7.7.2">
<h3><span class="header-section-number">7.7.2</span> Answer</h3>
<p>Prestige for professionals is 32.3 points greater than for blue collar workers (<span class="math inline">\(t = 14.5\)</span>, <span class="math inline">\(p &lt; .001\)</span>) and 25.6 points greater than for white collar workers (<span class="math inline">\(t = 9.8\)</span>, <span class="math inline">\(p &lt; .001\)</span>).</p>
</div>
</div>
<div id="checking-all-combinations" class="section level2" number="7.8">
<h2><span class="header-section-number">7.8</span> Checking all combinations</h2>
<p>It can quickly become a pain to use <code>relevel</code> like this and there are various alternatives.</p>
<p>At this point, I wish I hadn’t been so clever using a pipe and instead just saved the model. I shall do so now.</p>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="categorical-predictors-and-interactions.html#cb404-1" aria-hidden="true" tabindex="-1"></a>das_Model <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> type, <span class="at">data =</span> dat_no_NAs)</span></code></pre></div>
<p>We will use the <code>emmeans</code> package.</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="categorical-predictors-and-interactions.html#cb405-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code></pre></div>
<p>The main function therein is <code>emmeans</code>. Fox and Weisberg (2019, p. 203) comment that the formula argument is “idiosyncratic.” Anyway, here is how to use it:</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="categorical-predictors-and-interactions.html#cb406-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(das_Model, pairwise <span class="sc">~</span> type)</span></code></pre></div>
<pre><code>## $emmeans
##  type emmean   SE df lower.CL upper.CL
##  bc     35.5 1.43 95     32.7     38.4
##  prof   67.8 1.71 95     64.5     71.2
##  wc     42.2 1.98 95     38.3     46.2
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast  estimate   SE df t.ratio p.value
##  bc - prof   -32.32 2.23 95 -14.511 &lt;.0001 
##  bc - wc      -6.72 2.44 95  -2.748 0.0195 
##  prof - wc    25.60 2.61 95   9.795 &lt;.0001 
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>The first parameter is the name of the model, the second is a formula specifying which comparisons are required. The idiosyncracy in the model specification is that “pairwise” is not a variable in the data – it’s a type of comparison.</p>
<p>Compare and contrast with the results obtained by using <code>relevel</code> above.</p>
<p>The estimates are identical. One difference you will observe is that the p-values are adjusted for the number of comparisons. There has been an enormous quantity of ink spilled on the problem of multiple comparisons. You may recall a variety of corrections, often named after their creators, e.g., Bonferroni, Bonferroni-Holm (my favourite), and Šidák.</p>
<p>Here, the p-values are adjusted by “tukey method” which is Tukey’s Honest Significant Differences (HSD) adjustment. (Tukey is another statistician.)</p>
</div>
<div id="the-intercept-is-not-always-the-mean-of-the-comparison-group" class="section level2" number="7.9">
<h2><span class="header-section-number">7.9</span> The intercept is not always the mean of the comparison group</h2>
<p>The intercept always works the same way: it is the mean of the outcome variable when the predictors are zero. In the examples we have looked at, this was the mean of the comparison group – whatever happened to be the first level of the factor.</p>
<p>Let’s try another model:</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="categorical-predictors-and-interactions.html#cb408-1" aria-hidden="true" tabindex="-1"></a>more_data <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb408-2"><a href="categorical-predictors-and-interactions.html#cb408-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(occ, prestige, type, income) <span class="sc">%&gt;%</span></span>
<span id="cb408-3"><a href="categorical-predictors-and-interactions.html#cb408-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb408-4"><a href="categorical-predictors-and-interactions.html#cb408-4" aria-hidden="true" tabindex="-1"></a>type_and_income <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> <span class="fu">I</span>(income<span class="sc">/</span><span class="dv">1000</span>) <span class="sc">+</span> type, <span class="at">data =</span> more_data)</span>
<span id="cb408-5"><a href="categorical-predictors-and-interactions.html#cb408-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(type_and_income)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ I(income/1000) + type, data = more_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -20.2141  -6.7359  -0.1931   5.1725  25.0776 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     27.9971     1.8008  15.547  &lt; 2e-16 ***
## I(income/1000)   1.4012     0.2434   5.757 1.07e-07 ***
## typeprof        25.0555     2.3020  10.884  &lt; 2e-16 ***
## typewc           7.1672     2.1140   3.390  0.00102 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.21 on 94 degrees of freedom
## Multiple R-squared:  0.7765, Adjusted R-squared:  0.7693 
## F-statistic: 108.8 on 3 and 94 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now the intercept is <em>not</em> the mean prestige for blue collar workers, but rather it is predicted mean prestige for blue collar workers when income is zero.</p>
<p>By the way, we can use <code>emmeans</code> again to compare occupation types, holding income constant:</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="categorical-predictors-and-interactions.html#cb410-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(type_and_income, pairwise <span class="sc">~</span> type)</span></code></pre></div>
<pre><code>## $emmeans
##  type emmean   SE df lower.CL upper.CL
##  bc     37.7 1.30 94     35.1     40.3
##  prof   62.8 1.72 94     59.4     66.2
##  wc     44.9 1.77 94     41.4     48.4
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast  estimate   SE df t.ratio p.value
##  bc - prof   -25.06 2.30 94 -10.884 &lt;.0001 
##  bc - wc      -7.17 2.11 94  -3.390 0.0029 
##  prof - wc    17.89 2.63 94   6.809 &lt;.0001 
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
</div>
<div id="recap" class="section level2" number="7.10">
<h2><span class="header-section-number">7.10</span> Recap</h2>
<p>Okay, we have covered rather a lot of ground there so let me summarise a swift method for testing whether a categorical predictor explains variance in some outcome. I’ll use an example where we also statistically adjust for another predictor (known as a covariate).</p>
<p>First, do whatever you need to do to obtain and tidy the data:</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="categorical-predictors-and-interactions.html#cb412-1" aria-hidden="true" tabindex="-1"></a>more_data <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb412-2"><a href="categorical-predictors-and-interactions.html#cb412-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(occ, prestige, type, income) <span class="sc">%&gt;%</span></span>
<span id="cb412-3"><a href="categorical-predictors-and-interactions.html#cb412-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code></pre></div>
<p>Fit the model of interest:</p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="categorical-predictors-and-interactions.html#cb413-1" aria-hidden="true" tabindex="-1"></a>my_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> <span class="fu">I</span>(income<span class="sc">/</span><span class="dv">1000</span>) <span class="sc">+</span> type, <span class="at">data =</span> more_data)</span></code></pre></div>
<p>Use <code>Anova</code> to see which predictors are statistically significant</p>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="categorical-predictors-and-interactions.html#cb414-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(my_model)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: prestige
##                Sum Sq Df F value    Pr(&gt;F)    
## I(income/1000) 2234.5  1  33.147 1.068e-07 ***
## type           7988.5  2  59.251 &lt; 2.2e-16 ***
## Residuals      6336.7 94                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Look at a summary:</p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="categorical-predictors-and-interactions.html#cb416-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ I(income/1000) + type, data = more_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -20.2141  -6.7359  -0.1931   5.1725  25.0776 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     27.9971     1.8008  15.547  &lt; 2e-16 ***
## I(income/1000)   1.4012     0.2434   5.757 1.07e-07 ***
## typeprof        25.0555     2.3020  10.884  &lt; 2e-16 ***
## typewc           7.1672     2.1140   3.390  0.00102 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.21 on 94 degrees of freedom
## Multiple R-squared:  0.7765, Adjusted R-squared:  0.7693 
## F-statistic: 108.8 on 3 and 94 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Use <code>emmeans</code> to check for any comparisons of interest which were not included in the way the factor was initially setup:</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="categorical-predictors-and-interactions.html#cb418-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(my_model, pairwise <span class="sc">~</span> type)</span></code></pre></div>
<pre><code>## $emmeans
##  type emmean   SE df lower.CL upper.CL
##  bc     37.7 1.30 94     35.1     40.3
##  prof   62.8 1.72 94     59.4     66.2
##  wc     44.9 1.77 94     41.4     48.4
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast  estimate   SE df t.ratio p.value
##  bc - prof   -25.06 2.30 94 -10.884 &lt;.0001 
##  bc - wc      -7.17 2.11 94  -3.390 0.0029 
##  prof - wc    17.89 2.63 94   6.809 &lt;.0001 
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>Don’t forget to check model diagnostics…</p>
</div>
<div id="challenge" class="section level2 tabset" number="7.11">
<h2><span class="header-section-number">7.11</span> Challenge</h2>
<div id="activity-26" class="section level3" number="7.11.1">
<h3><span class="header-section-number">7.11.1</span> Activity</h3>
<ol style="list-style-type: lower-alpha">
<li><p>Fit a regression model with income as the outcome variable and occupation type as a predictor. Does type explain variance in outcome?</p></li>
<li><p>Is there a statistically significant difference between blue collar and white collar salaries?</p></li>
<li><p>Is there a statistically significant difference between white collar and professional salaries?</p></li>
<li><p>Are the residuals normally distributed?</p></li>
<li><p>Try logging income to see what impact it has on the residual distribution</p></li>
<li><p>Now compare all differences between groups</p></li>
</ol>
</div>
<div id="answers-1" class="section level3" number="7.11.2">
<h3><span class="header-section-number">7.11.2</span> Answers</h3>
<p><strong>a. Fit a regression model with income as the outcome variable and occupation type as a predictor. Does type explain variance in outcome?</strong></p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="categorical-predictors-and-interactions.html#cb420-1" aria-hidden="true" tabindex="-1"></a>income_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(income <span class="sc">~</span> type, <span class="at">data =</span> dat)</span>
<span id="cb420-2"><a href="categorical-predictors-and-interactions.html#cb420-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(income_mod)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: income
##               Sum Sq Df F value    Pr(&gt;F)    
## type       595956156  2  24.872 2.057e-09 ***
## Residuals 1138123006 95                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Yes: <span class="math inline">\(F(2,95) = 24.87\)</span>, <span class="math inline">\(p &lt; .001\)</span></p>
<p><strong>b. Is there a statistically significant difference between blue collar and white collar salaries?</strong></p>
<p>First, let’s have a look at the means, to help aid interpretation:</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="categorical-predictors-and-interactions.html#cb422-1" aria-hidden="true" tabindex="-1"></a>dat <span class="sc">%&gt;%</span></span>
<span id="cb422-2"><a href="categorical-predictors-and-interactions.html#cb422-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(type) <span class="sc">%&gt;%</span></span>
<span id="cb422-3"><a href="categorical-predictors-and-interactions.html#cb422-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_income =</span> <span class="fu">mean</span>(income))</span></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   type  mean_income
##   &lt;fct&gt;       &lt;dbl&gt;
## 1 bc          5374.
## 2 prof       10559.
## 3 wc          5052.
## 4 &lt;NA&gt;        3344.</code></pre>
<p>The means for blue collar and white collar look very similar, about $300 difference. Let’s test that difference:</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="categorical-predictors-and-interactions.html#cb424-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(income_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = income ~ type, data = dat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5945.5 -2003.3  -466.2  1536.9 15319.5 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   5374.1      521.8  10.299  &lt; 2e-16 ***
## typeprof      5185.3      811.6   6.389 6.16e-09 ***
## typewc        -321.8      890.6  -0.361    0.719    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3461 on 95 degrees of freedom
##   (4 observations deleted due to missingness)
## Multiple R-squared:  0.3437, Adjusted R-squared:  0.3299 
## F-statistic: 24.87 on 2 and 95 DF,  p-value: 2.057e-09</code></pre>
<p>There is no statistically significant difference, <span class="math inline">\(t = 0.361\)</span>, <span class="math inline">\(p = .71\)</span>.</p>
<p><strong>c. Is there a statistically significant difference between white collar and professional salaries?</strong></p>
<p>We can refit the model using <code>relevel</code> like so:</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="categorical-predictors-and-interactions.html#cb426-1" aria-hidden="true" tabindex="-1"></a>income_mod_wc <span class="ot">&lt;-</span> <span class="fu">lm</span>(income <span class="sc">~</span> <span class="fu">relevel</span>(type, <span class="st">&quot;wc&quot;</span>), <span class="at">data =</span> dat)</span>
<span id="cb426-2"><a href="categorical-predictors-and-interactions.html#cb426-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(income_mod_wc)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = income ~ relevel(type, &quot;wc&quot;), data = dat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5945.5 -2003.3  -466.2  1536.9 15319.5 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               5052.3      721.7   7.000  3.6e-10 ***
## relevel(type, &quot;wc&quot;)bc      321.8      890.6   0.361    0.719    
## relevel(type, &quot;wc&quot;)prof   5507.1      952.5   5.782  9.4e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3461 on 95 degrees of freedom
##   (4 observations deleted due to missingness)
## Multiple R-squared:  0.3437, Adjusted R-squared:  0.3299 
## F-statistic: 24.87 on 2 and 95 DF,  p-value: 2.057e-09</code></pre>
<p>Yes, professional salaries are a mean $5507 more than white collar salaries (<span class="math inline">\(t = 5.78\)</span>, <span class="math inline">\(p &lt; .001\)</span>).</p>
<p><strong>d. Are the residuals normally distributed?</strong></p>
<p>The order of levels does not affect the residuals, so either model would do:</p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="categorical-predictors-and-interactions.html#cb428-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(<span class="fu">resid</span>(income_mod_wc))</span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-288-1.png" width="672" /></p>
<pre><code>## [1]  2 24</code></pre>
<p>Hmmmm something fishy for residuals above 5000. Let’s look at the histogram in case it is more obvious:</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="categorical-predictors-and-interactions.html#cb430-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(income_mod_wc))</span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-289-1.png" width="672" /></p>
<p>Looks like they are not normally distributed, though maybe driven by outliers?</p>
<p><strong>e. Try logging income to see what impact it has on the residual distribution</strong></p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="categorical-predictors-and-interactions.html#cb431-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>log_income <span class="ot">&lt;-</span> <span class="fu">log</span>(dat<span class="sc">$</span>income)</span>
<span id="cb431-2"><a href="categorical-predictors-and-interactions.html#cb431-2" aria-hidden="true" tabindex="-1"></a>log_income_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_income <span class="sc">~</span> type, <span class="at">data =</span> dat)</span></code></pre></div>
<p>Now the residuals look much better:</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="categorical-predictors-and-interactions.html#cb432-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(<span class="fu">resid</span>(log_income_mod))</span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-291-1.png" width="672" /></p>
<pre><code>## 68  2 
## 64  2</code></pre>
<p><strong>f. Now compare all differences between groups</strong></p>
<p>Let’s use <code>emmeans</code>:</p>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="categorical-predictors-and-interactions.html#cb434-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(log_income_mod, pairwise <span class="sc">~</span> type)</span></code></pre></div>
<pre><code>## $emmeans
##  type emmean     SE df lower.CL upper.CL
##  bc     8.51 0.0638 95     8.39     8.64
##  prof   9.16 0.0760 95     9.01     9.31
##  wc     8.46 0.0882 95     8.28     8.63
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast  estimate     SE df t.ratio p.value
##  bc - prof  -0.6452 0.0992 95 -6.507  &lt;.0001 
##  bc - wc     0.0562 0.1088 95  0.516  0.8636 
##  prof - wc   0.7014 0.1164 95  6.027  &lt;.0001 
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>Note that the estimates are on the log scale, e.g., the difference between professional and white collar salaries is 0.7 on the logged $1000s scale.</p>
</div>
</div>
<div id="brief-introduction-to-interactions" class="section level2" number="7.12">
<h2><span class="header-section-number">7.12</span> Brief introduction to interactions</h2>
<p>Fox and Weisberg (2019, pp. 207-224) say lots about interactions. In this tutorial I just want to mention briefly what they are and how to ask R to model them.</p>
<div id="what-is-an-interaction" class="section level3" number="7.12.1">
<h3><span class="header-section-number">7.12.1</span> What is an interaction?</h3>
<p>An interaction between two variables simply means that the relationship between the outcome and one of the variables is changed (or “moderated”) by the other variable.
For example, we found that occupation type explains variation in prestige. It is possible that the magnitude of differences between occupation types depend on mean income.</p>
<p>Interactions can also be used to test for intersectional effects. Discrimination may, for instance, depend on sexism and racism – both operate independently. However, additionally the differences between men and women on some variable like salary might also depend on ethnicity and/or on whether you are cisgender or transgender.</p>
<p>Arithmetically, an interaction between two variables, <em>A</em> and <em>B</em> is represented as a new variable which is <em>A</em> and <em>B</em> multiplied together. R does the coding for us.</p>
</div>
<div id="how-to-test-for-interactions-in-r" class="section level3" number="7.12.2">
<h3><span class="header-section-number">7.12.2</span> How to test for interactions in R</h3>
<p>This shows how to test for an interaction between income and occupation type.</p>
<p>Let’s select some data again:</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="categorical-predictors-and-interactions.html#cb436-1" aria-hidden="true" tabindex="-1"></a>dat_for_int <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb436-2"><a href="categorical-predictors-and-interactions.html#cb436-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(occ, prestige, type, income) <span class="sc">%&gt;%</span></span>
<span id="cb436-3"><a href="categorical-predictors-and-interactions.html#cb436-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code></pre></div>
<p>First, predict prestige from income (in thousands) and occupation type. This model has the so-called “main effects,” i.e., without any interaction.</p>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="categorical-predictors-and-interactions.html#cb437-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>income_1000s <span class="ot">&lt;-</span> dat<span class="sc">$</span>income<span class="sc">/</span><span class="dv">1000</span></span>
<span id="cb437-2"><a href="categorical-predictors-and-interactions.html#cb437-2" aria-hidden="true" tabindex="-1"></a>main_effect_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> income_1000s <span class="sc">+</span> type, <span class="at">data =</span> dat)</span>
<span id="cb437-3"><a href="categorical-predictors-and-interactions.html#cb437-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(main_effect_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ income_1000s + type, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -20.2141  -6.7359  -0.1931   5.1725  25.0776 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   27.9971     1.8008  15.547  &lt; 2e-16 ***
## income_1000s   1.4012     0.2434   5.757 1.07e-07 ***
## typeprof      25.0555     2.3020  10.884  &lt; 2e-16 ***
## typewc         7.1672     2.1140   3.390  0.00102 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.21 on 94 degrees of freedom
##   (4 observations deleted due to missingness)
## Multiple R-squared:  0.7765, Adjusted R-squared:  0.7693 
## F-statistic: 108.8 on 3 and 94 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We can then use <code>Anova</code> as before:</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="categorical-predictors-and-interactions.html#cb439-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(main_effect_mod)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: prestige
##              Sum Sq Df F value    Pr(&gt;F)    
## income_1000s 2234.5  1  33.147 1.068e-07 ***
## type         7988.5  2  59.251 &lt; 2.2e-16 ***
## Residuals    6336.7 94                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>There are effects for both income (<span class="math inline">\(F(1,94) = 33.1\)</span>, <span class="math inline">\(p &lt; .001\)</span>) and occupation type (<span class="math inline">\(F(2,94) = 59.3\)</span>, <span class="math inline">\(p &lt; .001\)</span>).</p>
<p>Now, do differences between occupation types depend on income?</p>
<p>We can check as follows:</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="categorical-predictors-and-interactions.html#cb441-1" aria-hidden="true" tabindex="-1"></a>interaction_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> income_1000s <span class="sc">+</span> type <span class="sc">+</span></span>
<span id="cb441-2"><a href="categorical-predictors-and-interactions.html#cb441-2" aria-hidden="true" tabindex="-1"></a>                        income_1000s<span class="sc">:</span>type,</span>
<span id="cb441-3"><a href="categorical-predictors-and-interactions.html#cb441-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> dat)</span>
<span id="cb441-4"><a href="categorical-predictors-and-interactions.html#cb441-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(main_effect_mod, interaction_mod)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: prestige ~ income_1000s + type
## Model 2: prestige ~ income_1000s + type + income_1000s:type
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1     94 6336.7                                  
## 2     92 4859.2  2    1477.5 13.987 4.969e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>And the answer is, yes; <span class="math inline">\(F(2,92) = 14.0\)</span>, <span class="math inline">\(p &lt; .001\)</span>.</p>
<p>It is also possible to check both main effects (without interactions) and the interaction effect in one go:</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="categorical-predictors-and-interactions.html#cb443-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(interaction_mod)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: prestige
##                   Sum Sq Df F value    Pr(&gt;F)    
## income_1000s      2234.5  1  42.306 3.999e-09 ***
## type              7988.5  2  75.623 &lt; 2.2e-16 ***
## income_1000s:type 1477.5  2  13.987 4.969e-06 ***
## Residuals         4859.2 92                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The line beginning <code>income_1000s:type</code> shows the test of the interaction. To find out more about the <code>Anova</code> command and the Type II sum of squares it calculates by default, see Fox and Weisberg (2019, p. 262-264).</p>
</div>
<div id="understanding-interactions" class="section level3" number="7.12.3">
<h3><span class="header-section-number">7.12.3</span> Understanding interactions</h3>
<p>The most challenging aspect of interactions is that one can rapidly end up with enormously complex models which are difficult to interpret, even if everything is “statistically significant.” The secret to making sense of them is to plot model predictions. We will explore the <code>ggeffects</code> package – one easy way to do this – in more depth when examining logistic regression, but here is a preview of how it helps:</p>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="categorical-predictors-and-interactions.html#cb445-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb445-2"><a href="categorical-predictors-and-interactions.html#cb445-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpredict</span>(interaction_mod, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">&quot;income_1000s&quot;</span>, <span class="st">&quot;type&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb445-3"><a href="categorical-predictors-and-interactions.html#cb445-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">add.data =</span> <span class="cn">TRUE</span>, <span class="at">ci =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="R-notes_files/figure-html/unnamed-chunk-298-1.png" width="672" /></p>
<p>Hopefully this graph illustrates what it means that the relationship between income and prestige depends on occupation type – the slopes are different for each type.</p>
</div>
<div id="further-reading-1" class="section level3" number="7.12.4">
<h3><span class="header-section-number">7.12.4</span> Further reading</h3>
<p>You might be interested in Johnson-Neyman intervals. See the <a href="https://github.com/jacob-long/interactions/">interactions</a> package.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="linear-regression-diagnostics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="logistic-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["R-notes.pdf", "R-notes.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
